{ config, lib, pkgs, inputs, modulesPath, vars, ...}:
{
  # WARNING : This file was generated by d-setup.org
  # DO NOT MODIFY THIS FILE!
  # Any changes made here will be overwritten.

  imports = [

{
  boot = {
    # Uses bleeding edge latest kernel.
    kernelPackages = pkgs.linuxPackages_latest;
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
      timeout = 1;
    };
    initrd.availableKernelModules = [
      "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci"
    ];

    consoleLogLevel = 3;

    supportedFilesystems = [ "ntfs" ];
    tmp.cleanOnBoot = true;

    kernelParams = [
      "systemd.mask=dev-tpmrm0.device" #this is to mask that stupid 1.5 mins systemd bug
      "nowatchdog" "modprobe.blacklist=iTCO_wdt" #watchdog for Intel
      "quiet"
 	  ];
  };
}

# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "xe" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.kernelParams = [ "i915.force_probe=a7a0"  ];
# "intel_pstate=disable"

  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/af0bbf7a-ca6f-4823-b548-cc25c63c3d5e";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/68E2-CF64";
      fsType = "vfat";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}

{
  i18n = {
    defaultLocale = "en_US.UTF-8";
    # saves space
    supportedLocales = [ "en_US.UTF-8/UTF-8" "ja_JP.UTF-8/UTF-8" "ro_RO.UTF-8/UTF-8" ];
  };

  # Sets big font for bootloader, as I have small laptop.
  console = {
    earlySetup = true;
    font = "${pkgs.terminus_font}/share/consolefonts/ter-v32n.psf.gz";
    packages = with pkgs; [ terminus_font ];
    keyMap = "us";
  };
}

{
  # obviously your timezone here. Have a nice day or good night sleep ;)
  # Don't waste more time on nixos lol, be healthy and have some sleep. Stay healthy!
  time = {
    timeZone = "Asia/Kolkata";
    hardwareClockInLocalTime = true;
  };
}

{
  users.users.${vars.username} = {
    isNormalUser = true;
    shell = pkgs.fish;
    extraGroups = ["adbusers" "input" "uinput" "libvirtd" "networkmanager" "plugdev" "transmission" "video" "wheel"];
  };
}

{ # compresses half the ram for use as swap
  zramSwap = {
    enable = true;
    memoryPercent = 50;
    algorithm = "zstd";
  };
}

{
  systemd.sleep.extraConfig = ''
   AllowSuspendThenHibernate=yes
   HibernateDelaySec=3600
   AllowHibernation=yes
   '';
}

{
  networking = {
    hostName = "gdk";

    # Killer feature, Its a must these days.
    # Adblocker!! It uses steven black hosts.
    stevenblack = {
      enable = true;
      block = [ "fakenews" "gambling" "porn" ];
    };

    # mullvad dns
    nameservers = [ "194.242.2.9" "194.242.2.5" ];

    networkmanager = {
      enable = true;
      unmanaged = ["docker0" "rndis0" "interface-name:ve-*" ];
      # wifi.macAddress = "random"; # randomness? whitelist?
    };

    # Firewall uses iptables underthehood
    # Rules are for syncthing & kdeconnect
    firewall = rec {
      enable = true;
      allowedTCPPortRanges = [ { from = 1714; to = 1764; } ];
      allowedUDPPortRanges = allowedTCPPortRanges;
      allowedTCPPorts = [8384 22000];
      allowedUDPPorts = [22000 21027];
    };

    nat = { # for container or vm
      enable = true;
      internalInterfaces = ["ve-+"];
      externalInterface = "wlp0s20f3";
      # Lazy IPv6 connectivity for the container
      enableIPv6 = true;
    };

  };
}

{
  services = {
    openssh = { # ssh
      enable = true;
      settings.UseDns = true;
    };
    # DNS resolver
    resolved.enable = true;
  };
}

{
  # this makes our system more secure
  # note that it might break some stuff, eg webcam

  security = {
    protectKernelImage = true;
    rtkit.enable = true;
    polkit.enable = true;

    doas = {
      enable = true;
      extraRules = [{
        users = [ "${vars.username}" ];
        keepEnv = true;
        persist = true;
      }];
    };

    sudo.enable = false;
  };
}

{
  services = {
    getty = {
      greetingLine = "Greetings and Welcome back!";
      helpLine = "Let's learn more and get productive!";
    };
    atd.enable = true; # reminder tool, like @ 2:30 exec this
    fstrim.enable = true; # file system trim
  };
}

{ # For android file transfer via usb, or better could use KDE connect
  services.gvfs.enable = true;
}

{
  # For Laptop, make lid close and power buttom click to suspend
  services.logind = {
    lidSwitch = "suspend";
    extraConfig = ''
        HandlePowerKey=suspend
      '';
  };
}

{ # for fingerprint
  services.fprintd.enable = true;
}

{
  services.hardware.bolt.enable = true;
}

{
  services.power-profiles-daemon.enable = true;
}

{
  services = { # To mount drives with `udiskctl` command
    udisks2.enable = true;
    printing.enable = true;
  };
}

{
  services.syncthing = {
    enable = true;
    user = "${vars.username}";
    configDir = "/home/${vars.username}/.config/syncthing";
    dataDir = "/home/${vars.username}/.local/share/syncthing";
    overrideDevices = true;     # overrides any devices added or deleted through the WebUI
    overrideFolders = true;     # overrides any folders added or deleted through the WebUI
    settings = {
      devices = {
        "realme" = { id = "CEV3U3M-EJFLUJ3-UXFBEPG-KHX5EVK-3MSYH2W-BRNZEDH-TVJ4QWZ-X3G2CAW"; };
        #"device2" = { id = "DEVICE-ID-GOES-HERE"; };
      };
      folders = {
        "sync" = {
	        path = "~/d-sync";
	        devices = [ "realme" ];
        };
        "emacs" = {
	        path = "~/d-git/d-nix";
	        devices = [ "realme" ];
        };
        "theme" = {
	        path = "~/d-git/d-theme";
	        devices = [ "realme" ];
        };
        "site" = {
	        path = "~/d-git/d-site";
	        devices = [ "realme" ];
        };
      };
    };
  };
}

{
  environment = {
    variables = {
      VDPAU_DRIVER = lib.mkDefault "va_gl";
      BROWSER = "d-stuff";
      NIXOS_OZONE_WL = "1";
    };
    systemPackages = with pkgs; [
      gitFull
      (writeScriptBin "sudo" ''exec doas "$@"'')
    ];
  };
}

{
  environment = {
    # set channels (backwards compatibility)
    etc = {
      "nix/flake-channels/nixpkgs".source = inputs.nixpkgs;
      "nix/flake-channels/home-manager".source = inputs.home-manager;
    };
  };
}

{
  nixpkgs = {
    overlays = with inputs; [emacs-overlay.overlay];
    config = {
      allowUnfree = false;
      allowBroken = false;
    };
  };
}

{
  # Collect garbage and delete generation every 7 day. Will help to get some storage space.
  # Better to atleast keep it for few days, as you do major update (unstable), if something breaks you can roll back.
  nix = {
    optimise.automatic = true;
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 7d";
    };

    # Make builds run with low priority so my system stays responsive
    daemonCPUSchedPolicy = "idle";
    daemonIOSchedClass = "idle";

    # pin the registry to avoid downloading and evaling a new nixpkgs version every time
    registry = lib.mapAttrs (_: value: { flake = value; }) inputs;

    # This will additionally add your inputs to the system's legacy channels
    # Making legacy nix commands consistent as well, awesome!
    nixPath = lib.mapAttrsToList (key: value: "${key}=${value.to.path}") config.nix.registry;

    settings = {
      flake-registry = "/etc/nix/registry.json";
      extra-experimental-features = ["flakes" "nix-command" ];

      # use binary cache, its not gentoo
      substituters = [
        "https://nix-community.cachix.org"
      ];
      trusted-public-keys = [
        "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
      ];
    };
  };
}

{
  system.autoUpgrade.enable = false;
}

{
  programs.nix-ld.enable = true;
}

{ # disable for faster rebuilding
  documentation = {
    enable = true;
    doc.enable = true;
    info.enable = true;
    man = {
      enable = true;
      generateCaches = true; # will take little time
    };
    dev.enable = true;
  };
}

{
  hardware = {
    uinput.enable = true;
    cpu.intel.updateMicrocode = true;
    pulseaudio.enable = lib.mkForce false;
    graphics = {
      enable = true;
      enable32Bit = true;
      extraPackages = with pkgs; [
        libva intel-media-driver
        intel-vaapi-driver
        vaapiVdpau
        libvdpau-va-gl vpl-gpu-rt
      ];
      extraPackages32 = with pkgs.driversi686Linux; [
        intel-vaapi-driver intel-media-driver
      ];
    };
  };
}

{
  # Pipewire setup, just these lines enough to make sane default for it
  services.pipewire = {
    enable = true;
    alsa = {
      enable = true;
      support32Bit = true;
    };
    wireplumber.enable = true;
    pulse.enable = true;
    jack.enable = true;
  };

}

{
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
    # package = pkgs.bluez;
    # settings = {
    #   General = {
    #     FastConnectable = true;
    #     JustWorksRepairing = "always";
    #     Privacy = "device";
    #     Experimental = true;
    #   };
    # };
  };
  services.blueman.enable = true;
}

{
  programs = {
    niri.enable = true;
    xwayland.enable = true;
    };
}

{
  programs.hyprlock.enable = true; # for pam auth config
}

{
  fonts = {
    packages = with pkgs; [
      noto-fonts noto-fonts-emoji unifont
      # symbola # this font is unfree
      (callPackage ./pkgs/code-d-font.nix {})
      (callPackage ./pkgs/code-nika.nix {})
      merriweather atkinson-hyperlegible
      # (iosevka-bin.override { variant = "Aile"; }) nerd-fonts.iosevka
      # (iosevka-bin.override { variant = "Etoile"; })
    ];

    enableDefaultPackages = true;
  };
}

{
  stylix = {
    enable = true;
    image = ./configs/chinese-dragon.jpg;
    polarity = "dark";

    # base16Scheme = "${pkgs.base16-schemes}/share/themes/gruvbox-dark-hard.yaml";
    base16Scheme = {
      base00 = "#000000"; # bg
      base01 = "#333333"; # light bg
      base02 = "#303030"; # selection bg
      base03 = "#2e8b57"; # comment/hl
      base04 = "#D8DEE9"; # dim fg
      base05 = "#ffffff"; # fg
      base06 = "#6c7b8b"; # light fg
      base07 = "#444444"; # light bg
      base08 = "#ffb5c5"; # red
      base09 = "#ee9572"; # orange
      base0A = "#fbfba2"; # yellow
      base0B = "#54ff9f"; # green
      base0C = "#22fefe"; # aqua/cyan
      base0D = "#89b4fa"; # blue
      base0E = "#9370db"; # purple
      base0F = "#76eec6"; # brown
    };

    cursor = {
      package = pkgs.bibata-cursors;
      name = "Bibata-Modern-Classic";
      size = 12;
    };

    fonts = {
      serif = {
        package = pkgs.callPackage ./pkgs/code-nika.nix {};
        name = "Code Haki";
      };

      sansSerif = {
        package = pkgs.callPackage ./pkgs/code-nika.nix {};
        name = "Code Haki";
      };

      monospace = {
        package = pkgs.callPackage ./pkgs/code-nika.nix {};
        name = "Code OnePiece";
      };

      emoji = {
        package = pkgs.noto-fonts-emoji;
        name = "Noto Color Emoji";
      };

      sizes = {
        applications = 12;
        desktop = 12;
        popups = 12;
        terminal = 12;
      };

    };
  };

}

{
  programs.fish.enable = true;
}

{
  programs = {
    adb.enable = true; # help manage android devices via command#  line
    # fish.enable = true;
  };
}

];

  # stateVersion
  # NEVER EVER TOUCH THIS ⚠️
  system.stateVersion = lib.mkDefault "23.05"; # refer manual !

  # configuration ends here
}
