{ config, lib, pkgs, inputs, modulesPath, vars, ...}:
{
  # WARNING : This file was generated by d-setup.org
  # DO NOT MODIFY THIS FILE!
  # Any changes made here will be overwritten.

  imports = [

{
  boot = {
    # Uses bleeding edge latest kernel.
    kernelPackages = pkgs.linuxPackages_latest;
    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true; # maybe for dualboot
    };
    initrd.availableKernelModules = [
      "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci"
    ];

    supportedFilesystems = [ "ntfs" ];
    tmp.cleanOnBoot = true;

    kernelParams = [
      "systemd.mask=dev-tpmrm0.device" #this is to mask that stupid 1.5 mins systemd bug
      "nowatchdog" "modprobe.blacklist=iTCO_wdt" #watchdog for Intel
      # "mem_sleep_default=deep" # suspend to RAM (deep) rather than `s2idle`
      # ^ caused quick battery drain. With just ppd+suspend backup is good
 	  ];
  };
}

# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.initrd.kernelModules = [ "xe" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/209f8b3a-b7ae-44aa-bd18-b9f8965e57ab";
      fsType = "btrfs";
      options = [ "subvol=root" "compress=zstd" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/209f8b3a-b7ae-44aa-bd18-b9f8965e57ab";
      fsType = "btrfs";
      options = [ "subvol=home" "compress=zstd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/209f8b3a-b7ae-44aa-bd18-b9f8965e57ab";
      fsType = "btrfs";
      options = [ "subvol=nix" "compress=zstd" "noatime" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C30A-2932";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}

{
  time = {
    timeZone = "Asia/Kolkata";
  };
}

{
  users.users.${vars.username} = {
    isNormalUser = true;
    shell = pkgs.bash;
    extraGroups = ["adbusers" "input" "uinput" "libvirtd" "networkmanager" "plugdev" "transmission" "video" "wheel"];
  };
}

{ zramSwap.enable = true; }

{
  systemd.sleep.extraConfig = ''
   AllowSuspend=yes
   '';
}

{
  networking = {
    hostName = "gdk";

    # Killer feature, Its a must these days.
    # Adblocker!! It uses hagezi dns-blocklist
    hostFiles = [
      (pkgs.fetchurl {
        url = "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/ultimate-compressed.txt";
        hash = "sha256-aKViwYQs0+FMOluDawDSjzGoUjBZ+IpCp1zi453hcsg=";
      })
      (pkgs.fetchurl {
        url = "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/tif-compressed.txt";
        hash = "sha256-Ar2IGTlhCf1PKy/rntiaLfUULe8rVu/qrPiz7E9M8gc=";
      })

    ];

    # mullvad dns
    nameservers = [ "194.242.2.9" "194.242.2.5" ];

    networkmanager = {
      enable = true;
      unmanaged = ["docker0" "rndis0" "interface-name:ve-*" ];
      wifi.macAddress = "random"; # randomness? whitelist?
    };

    # Firewall uses iptables underthehood
    # Rules are for syncthing & kdeconnect
    firewall = rec {
      enable = true;
      allowedTCPPortRanges = [ { from = 1714; to = 1764; } ];
      allowedUDPPortRanges = allowedTCPPortRanges;
      allowedTCPPorts = [8384 22000];
      allowedUDPPorts = [22000 21027];
    };

    nat = { # for container or vm
      enable = true;
      internalInterfaces = ["ve-+"];
      externalInterface = "wlp0s20f3";
      # Lazy IPv6 connectivity for the container
      enableIPv6 = true;
    };

  };
}

{
  services = {
    openssh = { # ssh
      enable = true;
      settings = {
        UseDns = true;
        SetEnv = "TERM=xterm";
        };
    };
    # DNS resolver
    resolved.enable = true;
  };
}

{
  # this makes our system more secure
  # note that it might break some stuff, eg webcam

  security = {
    rtkit.enable = true;
    polkit.enable = true;

    doas = {
      enable = true;
      extraRules = [{
        users = [ "${vars.username}" ];
        keepEnv = true;
        persist = true;
      }];
    };

    sudo.enable = false;
  };
}

{
  services = {
    getty = {
      greetingLine = "Greetings and Welcome back!";
      helpLine = "Let's learn more and get productive!";
    };
    atd.enable = true; # reminder tool, like @ 2:30 | exec this
  };
}

{ # For android file transfer via usb, or better could use KDE connect
  services.gvfs.enable = true;
}

{
  # For Laptop, make lid close and power buttom click to suspend
  services.logind = {
    lidSwitch = "suspend";
    powerKey = "suspend";
  };
}

{
  services.hardware.bolt.enable = true;
}

{
  services.power-profiles-daemon.enable = true;
}

{
  services.thermald.enable = true;
}

{
  services = { # To mount drives with `udiskctl` command
    udisks2.enable = true;
    # printing.enable = true;
  };
}

{
  services.syncthing = {
    enable = true;
    user = "${vars.username}";
    configDir = "/home/${vars.username}/.config/syncthing";
    dataDir = "/home/${vars.username}/.local/share/syncthing";
    overrideDevices = true;     # overrides any devices added or deleted through the WebUI
    overrideFolders = true;     # overrides any folders added or deleted through the WebUI
    settings = let
      device_name = "dphone";
      in {
      devices = {
        "${device_name}" = { id = "CLVZ4YX-RS5G23W-4Y7TGV4-6P7G6DP-VNYUWIP-MQQGZXC-NCH56MN-O3FMAA5"; };
        #"device2" = { id = "DEVICE-ID-GOES-HERE"; };
      };
      folders = {
        "sync" = {
	        path = "~/d-sync";
	        devices = [ device_name ];
        };
        "emacs" = {
	        path = "~/d-git/d-nix";
	        devices = [ device_name ];
        };
      };
    };
  };
}

{
  environment = {
    variables = {
      BROWSER = "d-stuff";
      NIXOS_OZONE_WL = "1";
    };
    pathsToLink = [ "/share/xdg-desktop-portal" "/share/applications" ];
    systemPackages = with pkgs; [
      gitFull
      (writeScriptBin "sudo" ''exec doas "$@"'')
    ];
  };
}

{
  environment = {
    # set channels (backwards compatibility)
    etc = {
      "nix/flake-channels/nixpkgs".source = inputs.nixpkgs;
      "nix/flake-channels/home-manager".source = inputs.home-manager;
    };
  };
}

{
  nixpkgs = {
    overlays = with inputs; [emacs-overlay.overlay];
  };
}

{
  nix = {
    # pin the registry to avoid downloading and evaling a new nixpkgs version every time
    registry = lib.mapAttrs (_: value: { flake = value; }) inputs;

    # This will additionally add your inputs to the system's legacy channels
    # Making legacy nix commands consistent as well, awesome!
    nixPath = lib.mapAttrsToList (key: value: "${key}=${value.to.path}") config.nix.registry;

    settings = {
      flake-registry = "/etc/nix/registry.json";
      extra-experimental-features = ["flakes" "nix-command" ];
      warn-dirty = false;

      # use binary cache, its not gentoo
      substituters = [ "https://nix-community.cachix.org" ];
      trusted-public-keys = [ "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=" ];
    };
  };
}

{
  programs.nix-index-database.comma.enable = true;
  programs.nix-index.enable = true;
}

{ programs.nix-ld.enable = true; }

{
  programs.nh = {
    enable = true;
    clean.enable = true;
    clean.extraArgs = "--keep-since 4d --keep 3";
    flake = "/home/${vars.username}/d-git/d-nix";
  };
}

{ # disable for faster rebuilding
  documentation = {
    enable = true;
    doc.enable = true;
    info.enable = true;
    man = {
      enable = true;
      generateCaches = true; # will take little time
    };
    dev.enable = true;
  };
}

{
  hardware = {
    uinput.enable = true;
    graphics = {
      enable = true;
      enable32Bit = true;
      extraPackages = with pkgs; [ intel-media-driver intel-vaapi-driver libvdpau-va-gl mesa vulkan-loader vulkan-tools ];
      extraPackages32 = with pkgs.pkgsi686Linux; [
        vulkan-loader                        # Vulkan runtime (32-bit).
        driversi686Linux.mesa                # 32-bit Vulkan drivers for AMD/Intel.
        driversi686Linux.intel-media-driver  # Intel 32-bit media driver.
      ];

    };
  };
}

{
  services.pipewire = {
    enable = true;
    alsa = {
      enable = true;
      support32Bit = true;
    };
    wireplumber.enable = true;
    pulse.enable = true;
    jack.enable = true;
  };
}

{
  hardware.bluetooth = {
    enable = true;
  };
  services.blueman.enable = true;
}

{
  programs = {
    niri.enable = true;
    xwayland.enable = true;
    };
}

{
  programs.hyprlock.enable = true; # for pam auth config
}

{
  fonts = {
    packages = with pkgs; [
      noto-fonts noto-fonts-emoji unifont
      # symbola # this font is unfree
      (callPackage ./pkgs/code-d-font.nix {})
      (callPackage ./pkgs/code-nika.nix {})
      merriweather atkinson-hyperlegible
      # (iosevka-bin.override { variant = "Aile"; }) nerd-fonts.iosevka
      # (iosevka-bin.override { variant = "Etoile"; })
    ];

    enableDefaultPackages = true;
  };
}

{
  stylix = {
    enable = true;
    image = ./configs/chinese-dragon.jpg;
    polarity = "dark";

    base16Scheme = "${pkgs.base16-schemes}/share/themes/bright.yaml";

    cursor = {
      package = pkgs.layan-cursors;
      name = "layan-cursors";
      size = 24;
    };

    fonts = let
      dpkg = (pkgs.callPackage ./pkgs/code-d-font.nix {});

      # mpkg = pkgs.nerd-fonts.iosevka-term;
      # spkg = (pkgs.iosevka-bin.override { variant = "Aile"; });

      oppkg = pkgs.nerd-fonts._0xproto;
      orpkg = pkgs._0xpropo;
      plexpkg = pkgs.ibm-plex;
      blexpkg = pkgs.nerd-fonts.blex-mono;
      ipkg = pkgs.inter;

      mpkg = pkgs.maple-mono.NF;
      apkg = pkgs.aporetic-bin;

      # atnpkg = pkgs.atkinson-hyperlegible-next;
      # atmpkg = pkgs.atkinson-hyperlegible-mono;

    in {
      serif = {
        package = plexpkg;
        name = "IBM Plex Serif";
      };

      sansSerif = {
        package = plexpkg;
        name = "IBM Plex Sans";
      };

      monospace = {
        package = blexpkg;
        name = "BlexMono Nerd Font";
      };

      emoji = {
        package = pkgs.noto-fonts-emoji;
        name = "Noto Color Emoji";
      };

      sizes = {
        applications = 12;
        desktop = 12;
        popups = 12;
        terminal = 12;
      };

    };
  };

}

{
  programs.fish.enable = true;
}

{
  programs = {
    adb.enable = true; # help manage android devices via command#  line
    # fish.enable = true;
  };
}

{
  nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
    "aspell-dict-en-science"
  ];
}

];

  # stateVersion
  # NEVER EVER TOUCH THIS ⚠️
  system.stateVersion = lib.mkDefault "23.05"; # refer manual !

  # configuration ends here
}
