{pkgs, lib, config, vars, inputs, ...}:
{
  # WARNING : This file was generated by d-setup.org
  # DO NOT MODIFY THIS FILE!
  # Any changes made here will be overwritten.

  imports = [

{
  services = {
    gpg-agent = {
      enable = true;
      enableSshSupport = true;
      enableZshIntegration = true;
      # pinentryPackage = pkgs.pinentry-bemenu;
    };
  };
}

{
  services= {
    wlsunset = {
      enable = true;
      latitude = "19.0";
      longitude = "72.0";
      temperature.day = 6500;
      temperature.night = 4000;
      systemdTarget = "graphical-session.target";
    };
  };
}

{
  services.kdeconnect.enable = true;
}

{
  xdg = {
    enable = true;
    cacheHome = config.home.homeDirectory + "/.local/cache";

    mimeApps = let
      browser = ["d-stuff.desktop"];
    in {
      enable = true;

      defaultApplications = {
        "application/x-extension-htm" = browser;
        "application/x-extension-html" = browser;
        "application/x-extension-shtml" = browser;
        "application/x-extension-xht" = browser;
        "application/x-extension-xhtml" = browser;
        "application/xhtml+xml" = browser;
        "text/html" = browser;
        "x-scheme-handler/about" = browser;
        "x-scheme-handler/chrome" = ["chromium-browser.desktop"];
        "x-scheme-handler/ftp" = browser;
        "x-scheme-handler/http" = browser;
        "x-scheme-handler/https" = browser;
        "x-scheme-handler/unknown" = browser;

        "audio/*" = ["mpv.desktop"];
        "video/*" = ["mpv.dekstop"];
        "image/*" = ["imv.desktop"];
        "application/json" = browser;
        "application/pdf" = ["sioyek.desktop"];
        "x-scheme-handler/magnet" = ["d-stuff.desktop"];
        "application/epub+zip" = ["sioyek.desktop"];
        "application/zip" = ["sioyek.desktop"];
        "application/x.bittorrent" = ["d-stuff.desktop"];
      };

      associations.added = {
        "x-scheme-handler/magnet" = ["d-stuff.desktop"];
      };
    };

    userDirs = {
      enable = true;
      createDirectories = false;
      documents =  "${config.home.homeDirectory}/docs";
      download = "${config.home.homeDirectory}/dloads";
      videos = "${config.home.homeDirectory}/vids";
      music = "${config.home.homeDirectory}/music";
      pictures = "${config.home.homeDirectory}/pics";
      extraConfig = {
        xdg_screenshots_dir = "${config.xdg.userDirs.pictures}/sshots";
      };
    };

  };
  xdg.dataFile."applications/d-stuff.desktop".text = ''
  [Desktop Entry]
  Type=Application
  Name=Stuff Handler
  Exec=d-stuff %u
  '';

}

{
  imports = [
    inputs.nix-index-db.hmModules.nix-index
  ];
  programs.nix-index.enable = true;
}

{
  programs.man = {
    enable = true;
    generateCaches = true; # will take little time
  };
}

{
  programs = {

    gpg = {
      enable = true;
      homedir = "${config.xdg.dataHome}/gnupg";
      # to solve issue with emacs
      # package = pkgs.gnupg.overrideAttrs (orig: {
      #   version = "2.4.0";
      #   src = pkgs.fetchurl {
      #     url = "mirror://gnupg/gnupg/gnupg-2.4.0.tar.bz2";
      #     hash = "sha256-HXkVjdAdmSQx3S4/rLif2slxJ/iXhOosthDGAPsMFIM=";
      #   };
      # });
    };

    tealdeer = {
      enable = true;
      settings = {
        display = {
	        compact = false;
	        use_pager = true;
        };
        updates = {
	        auto_update = true;
        };
      };
    };
  };
}

{
  programs.git = {
    enable = true;
    package = pkgs.gitFull;

    delta = {
      enable = true;
      # TODOTHIS
      # options.map-styles = "bold purple => syntax ${default.xcolors.mauve}, bold cyan => syntax ${default.xcolors.blue}";
    };

    extraConfig = {
      diff.colorMoved = "default";
      merge.conflictstyle = "diff3";
    };

    aliases = {
      a = "add";
      b = "branch";
      c = "commit";
      ca = "commit --amend";
      cm = "commit -m";
      cho = "checkout";
      d = "diff";
      ds = "diff --staged";
      p = "push";
      pf = "push --force-with-lease";
      pl = "pull";
      l = "log";
      r = "rebase";
      s = "status --short";
      ss = "status";
      forgor = "commit --amend --no-edit";
      graph = "log --all --decorate --graph --oneline";
      logrep = "log --decorate --oneline --grep=";
      oops = "checkout --";
    };

    ignores = ["*~" "*.swp" "*result*" ".direnv" "node_modules"];

    # signing = {
    #   key = "";
    #   signByDefault = true;
    # };

    userEmail = "igoldlip@gmail.com";
    userName = "Dilip";
    # editor = "";
  };

}

{
  programs.direnv = {
    enable = true;
    nix-direnv.enable = true;
    enableZshIntegration = true;
  };
}

{
  programs.foot = {
    enable = true;

    # doesnt work properly; Enable it in hyprland or sway config
    server.enable = false;

    settings = {
      main = {
        term = "xterm-256color";
        font = "Code OnePiece:size=26, Noto Color Emoji:size=25";
        font-bold = "Code OnePiece:size=26, Noto Color Emoji:size=25";
        letter-spacing = "1";
        box-drawings-uses-font-glyphs = "no";
        pad = "0x0center";
        notify = "notify-send -a \${app-id} -i \${app-id} \${title} \${body}";
        selection-target = "clipboard";
        # dpi-aware = "true";
      };

      scrollback = {
        lines = 10000;
        multiplier = 3;
      };

      url = {
        launch = "d-stuff \${url}";
        label-letters = "sadfjklewcmpgh";
        osc8-underline = "url-mode";
        protocols = "http, https, ftp, ftps, file";
        uri-characters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_.,~:;/?#@!$&%*+=\"'()[]";
      };

      key-bindings = {
        clipboard-copy = "Control+Shift+c";
        clipboard-paste = "Control+Shift+v Control+y";
        primary-paste = "Shift+Insert";

      };

      colors = {
        background = "050505";
        foreground = "ffffff";
        regular0 = "030303";
        regular1 = "ff8059";
        regular2 = "44bc44";
        regular3 = "d0bc00";
        regular4 = "2fafff";
        regular5 = "feacd0";
        regular6 = "00d3d0";
        regular7 = "bfbfbf";
        bright0 = "595959";
        bright1 = "ef8b50";
        bright2 = "70b900";
        bright3 = "c0c530";
        bright4 = "79a8ff";
        bright5 = "b6a0ff";
        bright6 = "6ae4b9";
        bright7 = "ffffff";
        alpha = "0.9";
      };

      mouse = {
        hide-when-typing = "yes";
      };

    };
  };
}

{
  programs.zellij = {
    enable = true;
    settings = {

    };
  };
}

{
  # does not read local path properly. so ~/.local/bin does not work
  # may need exec from path then. Why? Just emacs --bg-daemon in WM
  # services.emacs = {
  #   enable = true;
  #   socketactivation.enable = true;
  # };

  home.packages = with pkgs; [
    emacs-lsp-booster
    imagemagick # for image-dired and other converts
  ];

  programs.emacs = {
    enable = true;
    package = pkgs.emacs-pgtk;
    extraPackages = (epkgs: (with epkgs; [
      treesit-grammars.with-all-grammars
      eat vundo undo-fu-session helpful
      no-littering rainbow-delimiters colorful-mode
      vertico orderless consult marginalia embark org-modern corfu cape corfu-terminal
      olivetti nerd-icons nerd-icons-completion nerd-icons-corfu nerd-icons-dired
      embark-consult consult-eglot markdown-mode nix-mode nix-ts-mode
      reddigg hnreader howdoyou magit webpaste
      shrface shr-tag-pre-highlight nov devdocs-browser reformatter
      tempel tempel-collection eglot-tempel
      sdcv jinx envrc dashboard mini-echo
      speed-type vc-backup aria2 pubmed
      ess auctex julia-mode webfeeder engrave-faces
      toc-org org-ql org-alert org-noter
      saveplace-pdf-view flycheck consult-flycheck
      ef-themes doom-themes
      org-re-reveal

      (trivialBuild {
        pname = "combobulate";
        version = "pre-2024-03-11";

        src = pkgs.fetchFromGitHub {
          owner = "mickeynp";
          repo = "combobulate";
          rev = "ee82c568ad639605518f62f82fae4bcc0dfdbb81";
          hash = "sha256-rww0/6304xZWTFRo1BVcfSDdXOXtlgmfZOxAoOIjYsk=";
        };
      })

      (trivialBuild {
        pname = "eglot-booster";
        version = "pre-2024-04-11";

        src = pkgs.fetchFromGitHub {
          owner = "jdtsmith";
          repo = "eglot-booster";
          rev = "e19dd7ea81bada84c66e8bdd121408d9c0761fe6";
          hash = "sha256-vF34ZoUUj8RENyH9OeKGSPk34G6KXZhEZozQKEcRNhs=";
        };
      })

      (trivialBuild {
        pname = "org-super-links";
        version = "pre-0.4";

        src = pkgs.fetchFromGitHub {
          owner = "toshism";
          repo = "org-super-links";
          rev = "0dd9ed22b4785f50c61051170db7c78b522a37ee";
          hash = "sha256-OWHUQBKp74sVIFbk8f7Xw7K11jPcR3HIVjpp5xiNwzs=";
        };
      })



      ## packages kept out to make more vanilla usage!
      # async dirvish beframe powerthesaurus meow
      # doom-modeline ox-hugo ement kind-icon el-patch
      # rainbow-mode -> replcaed by new package, colorful-mode
      # saveplace-pdf-view pdf-tools

    ])
    );
  };

  xdg.configFile."emacs/init.el".source = config.lib.file.mkOutOfStoreSymlink "/home/${vars.username}/d-git/d-nix/gdk/configs/d-emacs/init.el";

  xdg.configFile."emacs/early-init.el".source = config.lib.file.mkOutOfStoreSymlink "/home/${vars.username}/d-git/d-nix/gdk/configs/d-emacs/early-init.el";

}

{
  home.packages = with pkgs; [
    # better to manage it via development shell

    ##### core comp ####
    parallel
  ];
}

{
  home.packages = with pkgs; [
    # basic stack
    # nodepackages.vscode-langservers-extracted
    hugo monolith
  ];
}

{
  home.packages = with pkgs; [
    ##### science ####
    # blast ncbi sra_toolkit
    julia-bin
  ];
}

{
  home.packages = with pkgs; [
    texlive.combined.scheme-full
  ];
}

{
  programs.sioyek = {
    enable = true;
    bindings = {
      "move_up" = ["k" "<C-p>"];
      "move_down" = ["j" "<C-n>"];
      "move_left" = "h";
      "move_right" = "l";
      "screen_down" = [ "d" "<C-v>" ];
      "screen_up" = [ "u" "<A-v>" ];
      "fit_to_page_width" = "<f9>";
      "fit_to_page_width_smart" = "<f10>";
      "toggle_fullscreen" = [ "f" "<f11>"  ];
      "quit" = "q";
      "toggle_custom_color" = [ "<f8>" "I"];
      "toggle_highlight" = "<f1>";
      "command" = "<A-x>";
      "toggle_dark_mode" = "i";
      "toggle_presentation_mode" = "<f5>";
      "toggle_statusbar" = "B";
    };

    config = {
      "background_color" = "0.0 0.0 0.0";
      "dark_mode_background_color" = "0.0 0.0 0.0";
      "custom_background_color" = "0.9 0.8 0.7";
      "custom_text_color" = "0.0 0.0 0.0";
      "dark_mode_contrast" = "1.0";
      "text_highlight_color" = "1.0 1.0 0.0";
      "search_url_s" = "https://scholar.google.com/scholar?q";
      "search_url_l" = "http://gen.lib.rus.ec/scimag/?q";
      "search_url_g" = "https://www.google.com/search?q";
      "middle_click_search_engine" = "s";
      "shift_middle_click_search_engine" = "l";
      "zoom_inc_factor" = "1.2";
      "flat_toc" = "0";
      "should_launch_new_instance" = "1";
      "should_launch_new_window" = "1";
      "default_dark_mode" = "1";
      "sort_bookmarks_by_location" = "1";
      "ui_font" = "'Code D Haki'";
      "font_size" = "24";
      "wheel_zoom_on_cursor" = "1";
      "status_bar_font_size" = "22";
      "collapsed_toc" = "1";
      "ruler_mode" = "1";
      "single_click_selects_words" = "1";
      "item_list_prefix" = ">";
      "#ignore_whitespace_in_presentation_mode" = "0";
      "prerender_next_page_presentation" = "1";
      "display_resolution_scale" = "1.0";
    };
  };
}

{
  home.packages = with pkgs; [
    mupdf poppler_utils ghostscript # for doc-view
  ];
}

{
  home.packages = with pkgs; [
    mullvad-browser
    # ungoogled-chromium
    # nyxt
    # brave
  ];

  programs = {
    firefox = {
      enable = true;
      # package = pkgs.firefox-wayland; # is there difference?

      profiles.ihome = {
        isDefault = true;
        # extensions = with pkgs.nur.repos.rycee.firefox-addons; [
        #   ff2mpv
        #   vimium
        #   languagetool
        #   ublock-origin
        #   darkreader
        #   libredirect
        #   multi-account-containers
        # sideberry
        # ];

        # container = {
        #   dangerous = {
        #     color = "red";
        #     icon = "fruit";
        #     id = 2;
        #   };
        #   shopping = {
        #     color = "blue";
        #     icon = "cart";
        #     id = 1;
        #   };
        # };

        settings = {
          "browser.startup.homepage" = "about:blank";
          "browser.urlbar.placeholderName" = "Time to get Productive...";
          "gfx.webrender.all" = true;
          "gfx.webrender.enabled" = true;
          "media.peerconnection.enabled" = true;
          "media.av1.enabled" = false;
          "media.ffmpeg.vaapi.enabled" = true;
          "media.hardware-video-decoding.force-enabled" = true;
          "media.navigator.mediadatadecoder_vpx_enabled" = true;
          "signon.rememberSignons" = false;
          "app.normandy.api_url" = "";
          "app.normandy.enabled" = false;
          "app.shield.optoutstudies.enabled" = false;
          "beacon.enabled" = false;
          "breakpad.reportURL" = "";
          "browser.aboutConfig.showWarning" = false;
          "browser.cache.offline.enable" = false;
          "browser.crashReports.unsubmittedCheck.autoSubmit" = false;
          "browser.crashReports.unsubmittedCheck.autoSubmit2" = false;
          "browser.crashReports.unsubmittedCheck.enabled" = false;
          "browser.disableResetPrompt" = true;
          "browser.newtab.preload" = false;
          "browser.newtabpage.activity-stream.section.highlights.includePocket" = false;
          "extensions.pocket.enabled" = false;
          "browser.newtabpage.enhanced" = false;
          "browser.newtabpage.introShown" = true;
          "browser.safebrowsing.appRepURL" = "";
          "browser.safebrowsing.blockedURIs.enabled" = false;
          "browser.safebrowsing.downloads.enabled" = false;
          "browser.safebrowsing.downloads.remote.enabled" = false;
          "browser.safebrowsing.downloads.remote.url" = "";
          "browser.safebrowsing.enabled" = false;
          "browser.safebrowsing.malware.enabled" = false;
          "browser.safebrowsing.phishing.enabled" = false;
          "browser.selfsupport.url" = "";
          "browser.send_pings" = false;
          "browser.sessionstore.privacy_level" = 2;
          "browser.startup.homepage_override.mstone" = "ignore";
          "browser.tabs.crashReporting.sendReport" = false;
          "browser.urlbar.groupLabels.enabled" = false;
          "browser.urlbar.quicksuggest.enabled" = false;
          "browser.urlbar.speculativeConnect.enabled" = false;
          "datareporting.healthreport.service.enabled" = false;
          "datareporting.healthreport.uploadEnabled" = false;
          "datareporting.policy.dataSubmissionEnabled" = false;
          "device.sensors.ambientLight.enabled" = false;
          "device.sensors.enabled" = false;
          "device.sensors.motion.enabled" = false;
          "device.sensors.orientation.enabled" = false;
          "device.sensors.proximity.enabled" = false;
          "dom.battery.enabled" = false;
          "dom.event.clipboardevents.enabled" = true;
          "dom.webaudio.enabled" = false;
          "experiments.activeExperiment" = false;
          "experiments.enabled" = false;
          "experiments.manifest.uri" = "";
          "experiments.supported" = false;
          "extensions.getAddons.cache.enabled" = false;
          "extensions.getAddons.showPane" = false;
          "extensions.greasemonkey.stats.optedin" = false;
          "extensions.greasemonkey.stats.url" = "";
          "extensions.shield-recipe-client.api_url" = "";
          "extensions.shield-recipe-client.enabled" = false;
          "extensions.webservice.discoverURL" = "";
          "fission.autostart" = true;
          "media.autoplay.default" = 1;
          "media.autoplay.enabled" = false;
          "media.eme.enabled" = false;
          "media.gmp-widevinecdm.enabled" = false;
          "media.navigator.enabled" = false;
          "media.video_stats.enabled" = false;
          "network.IDN_show_punycode" = true;
          "network.allow-experiments" = false;
          "network.captive-portal-service.enabled" = false;
          "network.cookie.cookieBehavior" = 1;
          "network.dns.disablePrefetch" = true;
          "network.dns.disablePrefetchFromHTTPS" = true;
          "network.http.referer.spoofSource" = true;
          "network.http.speculative-parallel-limit" = 0;
          "dom.security.https_only_mode" = true;
          "network.predictor.enable-prefetch" = false;
          "network.predictor.enabled" = false;
          "network.prefetch-next" = false;
          "network.trr.mode" = 5;
          "privacy.donottrackheader.enabled" = true;
          "privacy.donottrackheader.value" = 1;
          "privacy.firstparty.isolate" = true;
          "privacy.trackingprotection.cryptomining.enabled" = true;
          "privacy.trackingprotection.enabled" = true;
          "privacy.trackingprotection.fingerprinting.enabled" = true;
          "privacy.trackingprotection.pbmode.enabled" = true;
          "privacy.usercontext.about_newtab_segregation.enabled" = true;
          "security.ssl.disable_session_identifiers" = true;
          "services.sync.prefs.sync.browser.newtabpage.activity-stream.showSponsoredTopSite" = false;
          "browser.newtabpage.activity-stream.showSponsored" = false;
          "signon.autofillForms" = false;
          "toolkit.telemetry.archive.enabled" = false;
          "toolkit.telemetry.bhrPing.enabled" = false;
          "toolkit.telemetry.cachedClientID" = "";
          "toolkit.telemetry.enabled" = false;
          "toolkit.telemetry.firstShutdownPing.enabled" = false;
          "toolkit.telemetry.hybridContent.enabled" = false;
          "toolkit.telemetry.newProfilePing.enabled" = false;
          "toolkit.telemetry.prompted" = 2;
          "toolkit.telemetry.rejected" = true;
          "toolkit.telemetry.reportingpolicy.firstRun" = false;
          "toolkit.telemetry.server" = "";
          "toolkit.telemetry.shutdownPingSender.enabled" = false;
          "toolkit.telemetry.unified" = false;
          "toolkit.telemetry.unifiedIsOptIn" = false;
          "toolkit.telemetry.updatePing.enabled" = false;
          "webgl.disabled" = true;
          "toolkit.legacyUserProfileCustomizations.stylesheets" = true;
          "webgl.renderer-string-override" = " ";
          "webgl.vendor-string-override" = " ";
          "browser.urlbar.update2.engineAliasRefresh" = true;
          "signon.passwordEditCapture.enabled" = false;
          "browser.search.hiddenOneOffs" = "Google,Yahoo,Bing,Amazon.com,Twitter";
          "browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts" = false;
          "browser.urlbar.trimURLs" = false;
          "findbar.modalHighlight" = true;
          "browser.fullscreen.autohide" = true;
          "browser.newtabpage.activity-stream.topSitesRows" = 0;
          "browser.urlbar.quickactions.enabled" = true;
          "pdfjs.annotationEditorMode" = 0;
          "pdfjs.annotationmode" = 2;
          "layers.acceleration.force-enabled" = true;
          "layout.css.backdrop-filter.enabled" = true;
          "svg.context-properties.content.enabled" = true;
          "full-screen-api.ignore-widgets" = true;
        };

        search = {
          default = "SearXNG";
          force = true;
          engines = {
            "SearXNG" = {
              urls = [{template = "https://searx.be/search?q={searchTerms}";}];
              updateInterval = 24 * 60 * 60 * 1000; # every day
              definedAliases = ["@sr"];
            };

            "Nixpkgs-Package Search" = {
              urls = [{template = "https://search.nixos.org/packages?channel=unstable&size=250&sort=relevance&type=packages&query={searchTerms}";}];
              iconUpdateURL = "https://nixos.org/favicon.png";
              updateInterval = 24 * 60 * 60 * 1000; # every day
              definedAliases = ["@nps"];
            };

            "Nixpkgs-Modules Search" = {
              urls = [{template = "https://search.nixos.org/options?channel=unstable&size=200&sort=relevance&query={searchTerms}";}];
              iconUpdateURL = "https://nixos.org/favicon.png";
              updateInterval = 24 * 60 * 60 * 1000; # every day
              definedAliases = ["@nms"];
            };

            "NixOS-Wiki Search" = {
              urls = [{template = "https://nixos.wiki/index.php?search={searchTerms}&go=Go";}];
              iconUpdateURL = "https://nixos.org/favicon.png";
              updateInterval = 24 * 60 * 60 * 1000; # every day
              definedAliases = ["@nws"];
            };

            "Home-Manager Search" = {
              urls = [{template = "https://mipmip.github.io/home-manager-option-search/?query={searchTerms}";}];
              iconUpdateURL = "https://nixos.org/favicon.png";
              updateInterval = 24 * 60 * 60 * 1000; # every day
              definedAliases = ["@hms"];
            };

            "GitHub-Code Search" = {
              urls = [{template = "https://github.com/search?q={searchTerms}&type=code";}];
              iconUpdateURL = "https://github.githubassets.com/favicons/favicon-dark.svg";
              updateInterval = 24 * 60 * 60 * 1000; # every day
              definedAliases = ["@gcs"];
            };

            "Noogle.dev Search" = {
              urls = [{template = "https://noogle.dev/?term=%22{searchTerms}%22";}];
              iconUpdateURL = "https://noogle.dev/favicon.png";
              updateInterval = 24 * 60 * 60 * 1000; # every day
              definedAliases = ["@ngd" "@nog"];
            };

            "Nixpkgs PRs" = {
              urls = [{template = "https://nixpk.gs/pr-tracker.html?pr={searchTerms}";}];
              iconUpdateURL = "https://nixos.org/favicon.png";
              updateInterval = 24 * 60 * 60 * 1000; # every day
              definedAliases = ["@npr"];
            };
          };

          order = [
            "SearXNG"
            "DuckDuckGo"
          ];
        };

        userChrome = builtins.readFile ./configs/userChrome.css;
      };
    };

  };
}

{
  services = {
    mpd = {
      enable = true;
      musicDirectory = config.xdg.userDirs.music;
      network = {
        listenAddress = "127.0.0.1";
        port = 6600;
        startWhenNeeded = true;
      };
      extraConfig = ''
      audio_output {
        type            "pipewire"
        name            "pipewire sound server"
      }
      auto_update "yes"
    '';
    };

    playerctld.enable = true;

  };

  # if mpd not working, check here
  # home.sessionvariables.mpd_host = config.services.mpd.network.listenaddress;
}

{
  programs = {
    mpv = {
      enable = true;
      scripts = with pkgs.mpvScripts; [ mpris manga-reader ];

      bindings = {
        l = "seek  5";
        h = "seek -5";
        k = "seek  30";
        j = "seek -30";
        J = "cycle sub";
        K = "cycle sub down";
        B = "no-osd add contrast -4; no-osd add brightness 4; show-text 'Black Level: \${brightness}'";
        N = "no-osd add contrast 4; no-osd add brightness -4; show-text 'Black Level: \${brightness}'";
      };

      config = {
        force-window = true;
        osc = true;
        hwdec = "auto-safe";
        vo = "gpu";
        profile = "gpu-hq";
        gpu-context = "wayland";
        sub-border-size = 4.0;
        sub-shadow-color = "0.0/0.0/0.0";
        sub-shadow-offset = 1;
        sub-auto = "fuzzy";
        msg-level = "all=error";
        ytdl-format = "bestvideo[height<1080]+bestaudio/best";
        # ytdl-format = "bestvideo";
        save-position-on-quit = true;
        slang = "eng,en,eng,english";
        alang = "jp,jpn,en,eng";
        sub-font = "impress bt";
        autofit = "50%";
        sub-font-size = "48";
        speed = "1.5";
      };

      profiles = {
        manga = {
          profile-desc = "Read Manga";
          profile-cond = "filename and filename:match('%.cbz$') or filename:match('%.cbr$') or filename:match('%.zip$') or filename:match('%.rar$') ~= nil";
          profile = "high-quality";
          dscale = "mitchell";
          deband = "no";
        };
      };

    };
  };
}

{
  programs = {
    yt-dlp = {
      enable = true;
      settings = {
        embed-thumbnail = true;
        embed-metadata = true;
        embed-subs = true;
        sub-langs = "en";
      };
    };
  };
}

{
  xdg.configFile."ytfzf/conf.sh".text = ''
  #video_pref="248+bestaudio/best"
  video_pref="[height<=1080]"
  sub_link_count=1
  show_thumbnails=0
  invidious_instance="https://vid.puffyan.us"
  external_menu () {
  bemenu -w 0.98 -l 24 -p '  play '
  # rofi -dmenu -i -config ~/.config/rofi/list.rasi -p '󰑈  play'
  }
  
  thumbnail_quality=high
  scrape=youtube
  #is_sort=1
  #search_sort_by=upload_date
  '';
}

{
  programs = {
    imv = {
      enable = true;
      settings = {
        # check man imv(5)
        options.background = "050505";
        aliases.x = "close";
        binds = {
          p = "prev";
          n = "next";
          "<Shift+D>" = "exec rm \"$imv_current_file\"; close";
          r = "exec mogrify -rotate 90 \"$imv_current_file\"";
        };
      };
    };
  };
}

{
  home.packages = with pkgs; [
    # audio control
    pavucontrol
    playerctl
    pulsemixer
    pamixer
    transmission_4-gtk

    mpc_cli
    ytfzf ani-cli ytmdl
    # freetube
    mangal
  ];
}

{
  # the thing is you won't get xdg-portal-hyprland
  # refer: https://github.com/nix-community/home-manager/issues/1167
  # # enable hyprland
  wayland.windowManager.hyprland = {
    enable = true;
    systemd.enable = true;

    extraConfig = ''
    source					= ~/.config/hypr/hyprsea.conf
    '';

    settings = {

      decoration = {
        rounding = 10;
        inactive_opacity = 0.8;
        active_opacity = 0.9;
        fullscreen_opacity = 1.0;
        dim_inactive = false;
        shadow_offset = "0 5";
        "col.shadow" = "rgba(00000099)";

        blur = {
          enabled = 1;
          size = 6;
          passes = 3;
          new_optimizations = true;
          ignore_opacity = true;
        };
      };

      "$mod" = "super";

      input = {
        kb_layout = "us";
        kb_options = "ctrl:nocaps";
        follow_mouse = 1;
        sensitivity = 0.1;
        #    repeat_delay = 250

        touchpad = {
          natural_scroll = "no";
          disable_while_typing = 1;
          clickfinger_behavior = 0; # double tap > right click
          middle_button_emulation = 1;
          tap-to-click = 1;
        };
      };

      general  =  {
        gaps_in = 5;
        gaps_out = 15;
        border_size = 2;
        "col.active_border" = "rgba(2e8b57ff) rgba(87cefaff) rgba(ffec8bff) rgba(ffaeb9ff) 90deg";
        "col.inactive_border" = "0xff382D2E";
        no_border_on_floating  =  false; # enable border on float window
        layout  =  "dwindle";
      };

      misc = {
        disable_hyprland_logo = true;
        disable_splash_rendering = true;
        mouse_move_enables_dpms = true;
        enable_swallow = true;
        swallow_regex = "^(foot)$";
        vrr = false;
      };

      animations = {
        enabled = true;
        bezier = "linear, 0.0, 0.0, 1.0, 1.0";
        animation = "borderangle, 1, 180, linear, loop"; #used by rainbow borders and rotating colors
      };

      dwindle = {
        pseudotile = true;
        preserve_split = true;
        force_split = true;
        no_gaps_when_only = false;
        default_split_ratio = 1.0;
        smart_split = false;
      };

      master = {
        new_on_top = false;
        allow_small_split = true;
        no_gaps_when_only = false;
      };

      gestures  =  {
        workspace_swipe = 1;
        workspace_swipe_distance = 400;
        workspace_swipe_invert = 1;
        workspace_swipe_min_speed_to_force = 30;
        workspace_swipe_cancel_ratio = 0.5;
      };

      bindm = [
        # mouse movements
        "$mod, mouse:272, movewindow"
        "$mod, mouse:273, resizewindow"
        "$mod alt, mouse:272, resizewindow"
      ];


    };
  };

  # naming it main.conf becuase hm writes hyprland.conf, so just as an import
  xdg.configFile."hypr/hyprsea.conf".source = config.lib.file.mkOutOfStoreSymlink "/home/${vars.username}/d-git/d-nix/gdk/configs/hyprsea.conf";
}

{
  home.packages = with pkgs; [
    # screenshot
    # grim slurp
    grimblast

    libnotify libsixel
    brightnessctl
    wtype
    swaybg
    # swayidle gtklock

    # utils
    # ocrscript
    wl-screenrec
    wl-clipboard
  ];
}

{
  services.hypridle = {
    enable = true;
    settings ={
      general = {
        lock_cmd = "pidof hyprlock || hyprlock";       # avoid starting multiple hyprlock instances.
        before_sleep_cmd = "loginctl lock-session";    # lock before suspend.
        after_sleep_cmd = "hyprctl dispatch dpms on";  # to avoid having to press a key twice to turn on the display.
        unlock_cmd = "notify-send 'Welcome back!'";
      };

      listener = [
        {
          timeout = 150;
          on-timeout = "brightnessctl -s set 10";         # set monitor backlight to minimum, avoid 0 on OLED monitor.
          on-resume = "brightnessctl -r";                 # monitor backlight restore.
        }
        {
          timeout = 210;
          on-timeout = "loginctl lock-session";
        }
        {
          timeout = 250;
          on-timeout = "hyprctl dispatch dpms off";
          on-resume = "hyprctl dispatch dpms on";
        }
        {
          timeout = 900;
          on-timeout = "systemctl suspend";
        }
      ];
    };
  };
}

{
  programs.hyprlock = {
    enable = true;
    settings = {
      background = [
        {
          path = "/home/idlip/.local/share/bg.jpg";
          blur_size = 8;
          blur_passes = 3;
        }
      ];

      input-field = [
        {
          size = "300, 50";
          monitor = "";
          dots_center = true;
          shadow_passes = 2;
          outline_thickness = 3;
          dots_size = 0.3;
          dots_spacing = 0.1;
          fade_on_empty = true;
          placeholder_text = "<i>Pass</i>";
          position = "0, 200";
          halign = "center";
          valign = "bottom";
        }
      ];

      label = [
        {
          color = "rgba(255, 255, 255, 1.0)";
          font_size = 35;
          text = ''
          cmd[update:1000] echo "<b> "$(date +'%A, %-d %B %Y @ %T')" </b>"
          '';
          position = "0, 0";
          halign = "center";
          valign = "bottom";
        }

        {
          color = "rgba(255, 255, 255, 1.0)";
          font_size = 35;
          text = ''
            $USER, Welcome back!
          '';
          position = "0, 100";
          halign = "center";
          valign = "bottom";
        }
      ];

      image =[
        {
          path = "/home/idlip/d-git/d-wallpapers/oled/one-piece.jpg";
          size = 200;
          rounding = -1;
          border_size = 2;
          reload_time = -1;
          position = "0, 350";
          halign = "center";
          valign = "bottom";
        }
      ];

    };
  };
}

{
  # cursor theme
  home.pointerCursor = {
    name = "Bibata-Modern-Classic";
    package = pkgs.bibata-cursors;
    size = 24;
    gtk.enable = true;
  };

  gtk = {
    enable = true;

    theme = {
      name = "adw-gtk3-dark";
      package = pkgs.adw-gtk3;
    };

    iconTheme = {
      name = "Papirus-Dark";
      package = pkgs.papirus-icon-theme;
    };

    font = {
      name = "Code Haki";
      size = 26;
    };

    gtk2.configLocation = "${config.xdg.configHome}/gtk-2.0/gtkrc";

    gtk3.extraConfig = {
      gtk-xft-antialias = 1;
      gtk-xft-hinting = 1;
      gtk-xft-hintstyle = "hintslight";
      gtk-xft-rgba = "rgb";
      gtk-key-theme-name = "Emacs";
    };

    gtk2.extraConfig = ''
    gtk-xft-antialias=1
    gtk-xft-hinting=1
    gtk-xft-hintstyle="hintslight"
    gtk-xft-rgba="rgb"
    gtk-key-theme-name="Emacs"
    '';

  };
}

{
  qt = {
    enable = true;
    # platformTheme = "gtk3";
    style.name = "adwaita-dark";
  };
}

{
  programs.waybar = {
    enable = true;

    settings = {
      mainBar = {
        layer = "top";
        position = "top";
        # height = 15;
        # spacing = 7;
        fixed-center = true;
        exclusive = true;

        modules-left = [
          "custom/launcher"
          "hyprland/workspaces"
          "wlr/taskbar"
          "hyprland/window"
          "hyprland/submap"
        ];

        modules-center = [
          "custom/recorder" "clock" "mpd" "mpris"
        ];

        modules-right = [ "tray" "network" "battery" "memory" "pulseaudio" "custom/power" ];

        "hyprland/workspaces" = {
          format = "{icon}";
          disable-scroll = true;
          all-outputs = true;
          active-only = false;
          show-special = true;
          on-click = "activate";
          format-icons = {
            active = "";
            default = "";
            "1" = "1";
            "2" = "2";
            "3" = "3";
            "4" = "4";
            "5" = "5";
            "6" = "6";
          };
        };

        "hyprland/window" = {
          "format" = "{}";
          "separate-outputs" = true;
          "max-length" = 35;
          "rewrite" = {
            "(.*) - Mozilla Firefox" = "🦊 $1";
            "(.*) - LibreWolf" = "🐺 $1";
            "(.*) - Brave" = "🦁 $1";
            "(.*) - GNU Emacs (.*)" = " $1";
            "(.*).epub(.*)" = "󰂽 $1";
            "(.*)foot" = " Terminal $1";
          };
        };

        "hyprland/submap" = {
          "format" = " {}";
          "max-length" = 14;
          "tooltip" = false;
        };

        "wlr/taskbar"=  {
          "format"=  "{icon}";
          "icon-size"=  18;
          "spacing"=  0;
          "tooltip-format"=  "{title}";
          "on-click"=  "activate";
          "on-click-middle"=  "close";
        };


        "custom/launcher" = {
          "format" = "";
          "tooltip" = false;
          "on-click" = "bemenu-run";
          "interval" = 86400;
        };

        "battery" =  {
          "bat" =  "BAT1";
          "interval" =  60;
          "states" =  {
            "good" = 95;
            "warning" = 40;
            "critical" = 20;
          };
          "max-length" =  25;
          "format" = "{icon} {capacity}%";
          "format-charging" = " {capacity}%";
          "format-plugged" = " {capacity}%";
          "format-alt" = "{time} {icon}";
          "format-icons" = ["󰂎" "󰁺" "󰁻" "󰁼" "󰁽" "󰁾" "󰁿" "󰂀" "󰂁" "󰂂" "󰁹"];

        };

        "mpd" = {
          "format" = "{stateIcon} {title}  ";
          "format-disconnected" = "  ";
          "format-stopped" = "  ";
          "title-len" = 20;
          "interval" = 10;
          "on-click" = "mpc toggle";
          "state-icons" = {
            "paused" = "";
            "playing" = "";
          };
          "tooltip-format" = "Mpd Connected";
          "tooltip-format-disconnected" = "";
        };

        "mpris" = {
          "format" = " {player_icon} {dynamic}";
          "format-paused" = "{status_icon} <i>{dynamic}</i>";
          "player-icons" = {
            "default" = "▶";
            "mpv" = "🎵";
          };
          "status-icons" = {
            "paused" = "󰏤";
          };
          "max-length" = 20;
        };

        "custom/power" = {
          "format" = "⏻";
          "on-click" = "d-power";
          "tooltip" = false;
          "interval" = 86400;
        };

        "clock" = {
          "format-alt" = " {:%a %d %b  %I:%M %p}";
          "format" = " {:%H:%M}";
          ##"timezones" = [ "Kolkata" ];
          ##"max-length" = 200;
          "interval" = 1;
          "calendar" = {
            "mode"           = "year";
            "mode-mon-col"   = 3;
            "weeks-pos"      = "right";
            "on-scroll"      = 1;
            "format" = {
              "months" =     "<span color='#ffead3'><b>{}</b></span>";
              "days" =       "<span color='#ecc6d9'><b>{}</b></span>";
              "weeks" =      "<span color='#99ffdd'><b>W{}</b></span>";
              "weekdays" =   "<span color='#ffcc66'><b>{}</b></span>";
              "today" =      "<span color='#ff6699'><b><u>{}</u></b></span>";
            };
          };
          "tooltip-format" = "<tt><small>{calendar}</small></tt>";
        };

        "tray" = {
          "icon-size" = 23;
          "spacing" = 10;
        };

        "cpu" = {
          "format" = " {usage: >3}%";
          "on-click" = "footclient -e btop";
        };

        "memory" = {
          "on-click" = "foot -e btop";
          "interval" = 30;
          "format" = " {percentage}%";
          "format-alt" = " {used}GB";
          "max-length" = 10;
        };

        "network" = {
          # "interface" = "wlp2s0";
          "format" = "⚠ Disabled";
          "format-wifi" = " {bandwidthDownBytes}  {bandwidthUpBytes}";
          "format-ethernet" = " {bandwidthDownBytes}  {bandwidthUpBytes}";
          "format-disconnected" = "⚠ Disconnected";
          "on-click" = "d-wifi";
          "interval" = 2;
        };

        "pulseaudio" = {
          "scroll-step" = 2;
          "format" = "{icon} {volume: >3}%";
          "format-bluetooth" = "{icon} {volume: >3}%";
          "format-muted" =" muted";
          "on-click" = "pamixer -t";
          "format-icons" = {
            "headphones" = "";
            "handsfree" = "";
            "headset" = "";
            "phone" = "";
            "portable" = "";
            "car" = "";
            "default" = ["" ""];
          };
        };

        "custom/recorder" = {
          "format" = "{}";
          "interval" = "once";
          "exec" = "echo ' '";
          "tooltip" = "false";
          "exec-if" = "pgrep wl-screenrec";
          "on-click" = "pkill -INT wl-screenrec";
          "signal" = 8;
        };

      };
    };
  };

  home.file.".config/waybar/style.css".source = config.lib.file.mkOutOfStoreSymlink "/home/${vars.username}/d-git/d-nix/gdk/configs/style.css";

}

{
  programs = {
    eza = {
      enable = true;
      extraOptions = ["--group-directories-first" "--header"];
      icons = true;
    };

    ripgrep = {
      enable = true;
      arguments = [
        "--max-columns-preview"
        "--colors=line:style:bold"
        "--ignore-case"
      ];
    };

    btop = {
      enable = true;
      settings = {
        color_theme = "default";
        theme_background = false;
        vim_keys = true;
        shown_boxes = "proc cpu";
        rounded_corners = true ;
        graph_symbol = "block";
        proc_sorting = "memory";
        proc_reversed = false;
        proc_gradient = true;
      };
    };

    bat = {
      enable = true;
      extraPackages = with pkgs.bat-extras; [ batdiff batman batgrep batwatch ];
      config = {
        pager = "less -fr";
        theme = "TwoDark";
      };
    };

    ssh.enable = true;

    fzf = {
      enable = true;
      colors = {
        bg = "#121212";
        "bg+" = "#2e8b57";
        fg = "#fdfdfd";
        "fg+" = "#FFFFFF";
      };
      defaultCommand = "fd --type f";
    };

  };
}

{
  # symlink normal shell file to source for zsh
  home.file.".config/shell/source.sh".source = config.lib.file.mkOutOfStoreSymlink "/home/${vars.username}/d-git/d-nix/gdk/configs/source.sh";

  programs.zsh = {
    enable = true;
    dotDir = ".config/shell";
    autocd = true;
    enableCompletion = true;
    autosuggestion.enable = true;
    history.extended = true;

    dirHashes = {
      dl = "$HOME/dloads";
      docs = "$HOME/docs";
      code = "$HOME/d-git/codes";
      dots = "$HOME/d-git/d-nix";
      pics = "$HOME/pics";
      vids = "$HOME/vids";
      nixpkgs = "$HOME/d-git/forks/nixpkgs";
    };

    envExtra = ''
        #if [ -z $DISPLAY ] && [ "$(tty)" = "/dev/tty1" ]; then
        #  exec Hyprland
        #fi
    '';

    initExtra = ''
      source ~/.config/shell/source.sh

      source "${pkgs.zsh-syntax-highlighting}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
      source "${pkgs.zsh-history-substring-search}/share/zsh-history-substring-search/zsh-history-substring-search.zsh"
      source "${pkgs.zsh-autosuggestions}/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
      source "${pkgs.nix-zsh-completions}/share/zsh/plugins/nix/nix-zsh-completions.plugin.zsh"
      source "${pkgs.zsh-nix-shell}/share/zsh-nix-shell/nix-shell.plugin.zsh"
      source "${pkgs.zsh-autopair}/share/zsh/zsh-autopair/autopair.zsh"

    '';

    history = {
      save = 10000;
      size = 10000;
      expireDuplicatesFirst = true;
      ignoreDups = true;
      path = "${config.xdg.configHome}/shell/zsh_history";
    };
  };
}

{
  home.sessionVariables = {
    PATH = "$PATH:$HOME/d-git/d-bin/bin:$HOME/.local/bin";
    VISUAL = "$EDITOR";
    GRIM_DEFAULT_DIR = "$HOME/pics/sshots/";
    MANPAGER = "nvim +Man!";
    STARDICT_DATA_DIR = "$HOME/d-git/d-bin/treasure/dict/";
    LIBVA_DRIVER_NAME = "iHD";
    LESS = "-J -i -W --status-line --incsearch --use-color -R";
  };
}

{
  home.packages = with pkgs; [
    # archives
    zip
    unzip

    # wonderful spells

    ffmpeg-full sdcv nq
    # utils
    file
    du-dust
    fd
    wget
  ];
}

{
  programs.aria2 = {
    enable = true;
    settings = {
      dir = "/home/idlip/dloads";
      file-allocation = "none";
      log-level = "warn";
      split = "10";
      max-connection-per-server = 10;
      min-split-size = "5m";
      bt-max-peers = "0";
      bt-request-peer-speed-limit = "0";
      max-overall-upload-limit = "512k";
      bt-external-ip = "127.0.0.1";
      dht-listen-port = "6882";
      enable-dht = "true";
      enable-peer-exchange = "true";
      listen-port = "6881";
      bt-force-encryption = "true";
      bt-min-crypto-level = "arc4";
      bt-require-crypto = "true";
      follow-torrent = "mem";
      seed-ratio = "100";
      seed-time = "0";
      socket-recv-buffer-size = "1m";
      event-poll = "epoll";
      realtime-chunk-checksum = "true";
      allow-overwrite = "true";
      always-resume = "true";
      auto-file-renaming = "false";
      continue = "true";
      rpc-save-upload-metadata = "false";
    };
  };
}

{
  services.dunst = {
    enable = true;
    iconTheme = {
      package = pkgs.papirus-icon-theme;
      name = "Papirus";
    };
    settings = {
      global = {
        monitor = 0;
        background = "#050505";
        frame_color = "#2e8b57";
        transparency = 0;
        follow = "none";
        width = 400;
        height = 900;
        idle_threshold = 120;
        origin = "top-right";
        offset = "10x20";
        scale = 0;
        notification_limit = 0;
        progress_bar = "true";
        alignment = "center";
        progress_bar_height = 10;
        progress_bar_frame_width = 1;
        progress_bar_min_width = 150;
        progress_bar_max_width = 500;
        indicate_hidden = "yes";
        padding = 2;
        frame_width = 2;
        separator_color = "frame";
        sort = "yes";
        font = "Code Haki 26";
        line_height = 0;
        markup = "full";
        stack_duplicates = "true";
        vertical_alignment = "center";
        show_age_threshold = 60;
        ellipsize = "middle";
        ignore_newline = "no";
        show_indicators = "yes";
        icon_position = "left";
        max_icon_size = 32;
        sticky_history = "yes";
        history_length = 20;
        browser = "d-stuff";
        always_run_script = "true";
        title = "Dunst";
        class = "Dunst";
        corner_radius = 20;
        ignore_dbusclose = false;
        force_xwayland = "false";
        layer = "overlay";
        mouse_left_click = "do_action";
        mouse_middle_click = "do_action";
        mouse_right_click = "close_all";
      };

      reminder = {
        category = "reminder";
        background = "#33333390";
        foreground = "#ffffff";
        timeout = 0;
        script="d-notif";
      };

      urgency_low = {
        background = "#050505";
        foreground = "#ffffff";
        timeout = 5;
      };
      urgency_normal = {
        background = "#050505";
        foreground = "#ffffff";
        timeout = 6;
      };
      urgency_critical = {
        background = "#050505";
        foreground = "#ffffff";
        frame_color = "#f38ba8";
        timeout = 0;
      };
    };
  };
}

{
  services.cliphist.enable = true;
}

{
  home.packages = with pkgs; [
    openttd
    # zeroad
    superTux
    # supertuxkart
  ];
}

{
  # funny it just converts the set to commandLineArgs and puts it as home sessionVariables
  programs.bemenu = {
    enable = true;
    settings = {
      no-cursor = true;
      no-spacing = true;
      ignorecase = true;
      no-touch = true;
      prompt = " ";
      counter = "always";
      prefix = " ";

      fn = "Code Haki 28";

      nb = "#00000090";
      ab = "#00000090";
      bdr = "#c6daff";
      nf = "#ffffff";
      af = "#ffffff";
      hb = "#2e8b57";
      hf = "#000000";
      fb = "#111111";
      ff = "#fafad2";
      tb = "#121212";
      tf = "#6ae4b9";

    };
  };
}

{
  home.packages = with pkgs; [
    # misc
    libnotify
    # xdg-utils

    xfce.thunar
    libreoffice
    # pandoc
    groff mupdf
    keepassxc

  ];
}

{
  home.packages = with pkgs; [
    languagetool
    (aspellWithDicts (dicts: with dicts; [ en en-computers ]))
    hunspell hunspellDicts.en_US
  ];
}

];

  # NEVER EVER TOUCH IT ⚠️
  home.stateVersion = "23.05"; # refer manual !

  # home configuration ends here
}
