{pkgs, lib, config, vars, inputs, ...}:
{
  # WARNING : This file was generated by d-setup.org
  # DO NOT MODIFY THIS FILE!
  # Any changes made here will be overwritten.

  imports = [
	{
	   services = {
	    gpg-agent = {
	      enable = true;
	      enableExtraSocket = true;
	      enableSshSupport = true;
	      pinentry.package = pkgs.pinentry-gnome3; 
	      sshKeys = [ "1D0F13CF9061199762A8480B520999B9E78AE837" ];
	    };
	  };
	}
	{
	  programs = {
	    gpg = {
	      enable = true;
	      homedir = "${config.xdg.dataHome}/gnupg";
	      # homedir = "${config.home.homeDirectory}/d-sync/keys/gpg";
	      settings = {
	        default-key = "igoldlip@gmail.com";
	        default-recipient-self = true;
	      };
	    };
	  };
	}
	
	{ services.kdeconnect.enable = true; }
	{
	  services.easyeffects = {
		enable = true;
		extraPresets = {
		  better-mic = {
			input = {
			  blocklist = [ ];
			  "plugins_order" = [
				"rnnoise#0" "speex#0" "deepfilternet#0"
			  ];
			  "rnnoise#0" = {
				bypass = false;
				"enable-vad" = false;
				"input-gain" = 0.0;
				"model-path" = "";
				"output-gain" = 0.0;
				release = 20.0;
				"vad-thres" = 50.0;
				wet = 0.0;
			  };
			  "deepfilternet#0" = {
	            "attenuation-limit" = 100.0;
	            "max-df-processing-threshold" = 20.0;
	            "max-erb-processing-threshold" = 30.0;
	            "min-processing-buffer" = 0;
	            "min-processing-threshold" = -10.0;
	            "post-filter-beta" = 0.02;
	          };
			  "speex#0" = {
	            "bypass" = false;
	            "enable-agc" = true;
	            "enable-denoise" = true;
	            "enable-dereverb" = true;
	            "input-gain" = 0.0;
	            "noise-suppression" = -70;
	            "output-gain" = 0.0;
	            "vad" = {
	              "enable" = true;
	              "probability-continue" = 90;
	              "probability-start" = 95;
				};
	          };
			};
		  };
		};
	  };
	}
	{
	  xdg = {
	    enable = true;
	    cacheHome = config.home.homeDirectory + "/.local/cache";
	    userDirs = {
	      enable = true;
	      createDirectories = false;
	      documents =  "${config.home.homeDirectory}/docs";
	      download = "${config.home.homeDirectory}/dloads";
	      videos = "${config.home.homeDirectory}/media/vids";
	      music = "${config.home.homeDirectory}/media/music";
	      pictures = "${config.home.homeDirectory}/media/pics";
	      desktop = "${config.home.homeDirectory}/.local/share/desktop";
	      publicShare = "${config.home.homeDirectory}/.local/share/public";
	      templates = "${config.home.homeDirectory}/.local/share/templates";
	      extraConfig = {
	        xdg_screenshots_dir = "${config.xdg.userDirs.pictures}";
	      };
	    };
	
	    mimeApps = {
	      enable = true;
	      defaultApplications = {
	        "x-scheme-handler/magnet"="d-stuff.desktop";
	        "application/x-bittorrent"="d-stuff.desktop";
	        "application/postscript"="sioyek.desktop";
	        "application/pdf"="sioyek.desktop";
	        "image/png"="swayimg.desktop";
	        "image/jpeg"="swayimg.desktop";
	        "image/gif"="swayimg.desktop";
	        "application/rss+xml"="d-stuff.desktop";
	        "x-scheme-handler/mailto"="emacsmail.desktop";
	      };
	    };
	
		portal = {
	      enable = true;
	      config = {
			common = {
	          default = ["gtk" "gnome"];
	          "org.freedesktop.impl.portal.ScreenCast" = "gnome";
	          "org.freedesktop.impl.portal.Screenshot" = "gnome";
	          "org.freedesktop.impl.portal.RemoteDesktop" = "gnome";
	        };
		  };
	      configPackages = [ pkgs.niri ];
	      xdgOpenUsePortal = true;
	      extraPortals = with pkgs; [
			xdg-desktop-portal xdg-desktop-portal-gtk xdg-desktop-portal-gnome
	      ];
		};
	
	  };
	  xdg.dataFile."applications/d-stuff.desktop".text = ''
	    [Desktop Entry]
	    Type=Application
	    Name=Stuff Handler
	    Exec=d-stuff %u
	  '';
	
	}
	{
	  programs.man = {
	    enable = true;
	    generateCaches = true; # will take little time
	  };
	}
	{
	  programs.git = {
	    enable = true;
	    package = pkgs.gitFull;
	    settings = {
	      safe.directory = "...";
	      user = {
	        name = "Dilip";
	        email = "igoldlip@gmail.com";
	      };
	
	      alias = {
	        a = "add";
	        b = "branch";
	        c = "commit";
	        ca = "commit --amend";
	        cm = "commit -m";
	        cho = "checkout";
	        d = "diff";
	        ds = "diff --staged";
	        p = "push";
	        pf = "push --force-with-lease";
	        pl = "pull";
	        l = "log";
	        r = "rebase";
	        s = "status --short";
	        ss = "status";
	        forgor = "commit --amend --no-edit";
	        graph = "log --all --decorate --graph --oneline";
	        logrep = "log --decorate --oneline --grep=";
	        oops = "checkout --";
	      };
	    };
	
	    ignores = ["*~" "*.swp" "*result*" ".direnv" "node_modules"];
	
	    signing = {
	      key = "53F3BDB57ED8DC48";
	      signByDefault = true;
	    };
	  };
	
	}
	{
	  programs.direnv = {
	    enable = true;
	    nix-direnv.enable = true;
	  };
	}
	{
	  programs.foot = {
	    enable = true;
	    # server.enable = true; # use emacs dude!
	    settings = {
	      main = {
	        selection-target = "clipboard";
	      };
	      scrollback = {
	        lines = 10000;
	        multiplier = 3;
	      };
	      key-bindings = {
	        clipboard-copy = "Control+Shift+c";
	        clipboard-paste = "Control+Shift+v Control+y";
	        primary-paste = "Shift+Insert";
	      };
	      url = {
	        launch = "d-stuff \${url}";
	      };
	      mouse = {
	        hide-when-typing = "yes";
	      };
	    };
	  };
	}
	{
	  programs.zellij = {
	    enable = true;
	    settings = {
	    };
	  };
	}
	{
	  programs.emacs = {
	    enable = true;
	    package = pkgs.emacs-git-pgtk;
	    extraPackages = (epkgs: (with epkgs; [
	      treesit-grammars.with-all-grammars
	      vundo undo-fu-session
		  rainbow-delimiters colorful-mode
	      vertico orderless marginalia corfu cape
	      consult embark olivetti
	      # nerd-icons nerd-icons-completion nerd-icons-corfu nerd-icons-dired
	      embark-consult consult-eglot nix-ts-mode nix-mode
	      magit nov devdocs-browser reformatter
	      tempel eglot-tempel
	      jinx envrc ultra-scroll
	      # aria2 transmission
	      # ess 
	      # webfeeder engrave-faces
	      # toc-org
	      org-ql ox-hugo markdown-mode typst-ts-mode
	      flycheck consult-flycheck flycheck-eglot org-re-reveal
		  flycheck-vale
		  verb forge melpaPackages.telega melpaPackages.mastodon
	      # dslide
	
	      (melpaBuild {
	        pname = "combobulate";
	        version = "20250621";
	        src = pkgs.fetchFromGitHub {
	          owner = "mickeynp";
	          repo = "combobulate";
	          rev = "17c71802eed2df1a6b25199784806da6763fb90c";
	          hash = "sha256-m+06WLfHkdlMkLzP+fah3YN3rHG0H8t/iWEDSrct25E=";
	        };
	      })
	
	      (melpaBuild {
	        pname = "org-super-links";
	        version = "20250621";
	        src = pkgs.fetchFromGitHub {
	          owner = "toshism";
	          repo = "org-super-links";
	          rev = "ce04bd04b20c498f6deb6338aff142f312144e3b";
	          hash = "sha256-9SGb+imKyi6J+mpBtkheOLAIpmd0E55i0BOGBT617gE=";
	        };
	      })
	
	    ])
	    );
	  };
	
	  xdg.configFile."emacs/init.el".source = config.lib.file.mkOutOfStoreSymlink "/home/${vars.username}/d-git/d-nix/gdk/configs/d-emacs/init.el";
	
	  xdg.configFile."emacs/early-init.el".source = config.lib.file.mkOutOfStoreSymlink "/home/${vars.username}/d-git/d-nix/gdk/configs/d-emacs/early-init.el";
	
	}
	{
	  programs.sioyek = {
	    enable = true;
	    bindings = {
	      "move_up" = ["k" "<C-p>"];
	      "move_down" = ["j" "<C-n>"];
	      "move_left" = "h";
	      "move_right" = "l";
	      "screen_down" = [ "d" "<C-v>" ];
	      "screen_up" = [ "u" "<A-v>" ];
	      "fit_to_page_width" = "<f9>";
	      "fit_to_page_width_smart" = "<f10>";
	      "toggle_fullscreen" = [ "f" "<f11>"  ];
	      "quit" = "Q";
	      "toggle_custom_color" = [ "<f8>" "I"];
	      "toggle_highlight" = "<f1>";
	      "command" = "<A-x>";
	      "toggle_dark_mode" = "i";
	      "toggle_presentation_mode" = "<f5>";
	      "toggle_statusbar" = "B";
	      "[m]control_menu(move_to_begin)" = "<C-a>";
	      "[m]control_menu(move_to_end)" = "<C-e>";
	      "[m]control_menu(delete_to_end)" = "<C-k>";
	      "[m]control_menu(move_word_forward)" = "<A-f>";
	      "[m]control_menu(move_word_backward)" = "<A-b>";
	      "[m]control_menu('down')" = "<C-n";
	      "[m]control_menu('up')" = "<C-p>";
	    };
	
	    config = {
	      "background_color" = "0.0 0.0 0.0";
	      "dark_mode_background_color" = "0.0 0.0 0.0";
	      "custom_background_color" = "0.9 0.8 0.7";
	      "custom_text_color" = "0.0 0.0 0.0";
	      "dark_mode_contrast" = "1.0";
	      "text_highlight_color" = "1.0 1.0 0.0";
	      "search_url_s" = "https://scholar.google.com/scholar?q";
	      "search_url_l" = "http://gen.lib.rus.ec/scimag/?q";
	      "search_url_g" = "https://www.google.com/search?q";
	      "middle_click_search_engine" = "s";
	      "shift_middle_click_search_engine" = "l";
	      "flat_toc" = "0";
	      "default_dark_mode" = "1";
	      "sort_bookmarks_by_location" = "1";
	      "collapsed_toc" = "1";
	      "ruler_mode" = "1";
	      "single_click_selects_words" = "1";
	      "#ignore_whitespace_in_presentation_mode" = "0";
	      "prerender_next_page_presentation" = "1";
	    };
	  };
	}
	{
	  home.packages = [ (pkgs.callPackage ./pkgs/glide.nix {}) ];
	  programs.librewolf = {
	    enable = true;
	    profiles.ihome = {
	      extraConfig = ''
	         // ~/.librewolf/ihome/user.js
	        // userchrome.css usercontent.css activate
	        user_pref("sidebar.animation.expand-on-hover.duration-ms", "50");
	        user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
	        
	        // firefox sync
	        user_pref("identity.fxaccounts.enabled", true);
	        
	        // Fill SVG Color
	        user_pref("svg.context-properties.content.enabled", true);
	        
	        // CSS's `:has()` selector
	        user_pref("layout.css.has-selector.enabled", true);
	        
	        // Integrated calculator at urlbar
	        user_pref("browser.urlbar.suggest.calculator", true);
	        
	        // Integrated unit convertor at urlbar
	        user_pref("browser.urlbar.unitConversion.enabled", true);
	        user_pref("browser.tabs.insertAfterCurrent", true);
	        
	        // Trim  URL
	        user_pref("browser.urlbar.trimHttps", true);
	        user_pref("browser.urlbar.trimURLs", true);
	        
	        // GTK rounded corners
	        user_pref("widget.gtk.rounded-bottom-corners.enabled", true);
	        
	        // Who is bogus? (fixes Sidebery tab dragging on Linux)
	        user_pref("widget.gtk.ignore-bogus-leave-notify", 1);
	        
	        // for librewolf
	        user_pref("privacy.clearOnShutdown.history", false);
	        user_pref("privacy.clearOnShutdown.sessions", false);
	        user_pref("privacy.clearOnShutdown_v2.cookiesAndStorage", false);
	        user_pref("privacy.clearOnShutdown_v2.cache", false);
	        user_pref("privacy.clearOnShutdown.downloads", false);
	        
	         //user_pref("pdfjs.forcePageColors", true);
	         //user_pref("pdfjs.pageColorsBackground", "#000000");
	         //user_pref("pdfjs.pageColorsForeground", "#ffffff");
	        
	        user_pref("layout.css.grid-template-masonry-value.enabled", true);
	        user_pref("dom.enable_web_task_scheduling", true);
	        
	        // Better fox
	        user_pref("urlclassifier.trackingSkipURLs", "*.reddit.com, *.twitter.com, *.twimg.com");
	        user_pref("urlclassifier.features.socialtracking.skipURLs", "*.instagram.com, *.twitter.com, *.twimg.com");
	        
	        /** OCSP & CERTS / HPKP ***/
	        // Use CRLite instead of OCSP
	        user_pref("security.OCSP.enabled", 0);
	        user_pref("security.OCSP.require", false);
	        user_pref("security.pki.crlite_mode", 2);
	        
	        /** RFP ***/
	        // Limits refresh rate to 60mHz, breaks timezone, and forced light theme
	        // [1] https://librewolf.net/docs/faq/#what-are-the-most-common-downsides-of-rfp-resist-fingerprinting
	        user_pref("privacy.resistFingerprinting", false);
	        
	        // WebGL
	        // Breaks Map sites, NYT articles, Nat Geo, and more
	        // [1] https://manu.ninja/25-real-world-applications-using-webgl/
	        user_pref("webgl.disabled", false);
	        user_pref("gfx.webrender.all", true);
	        
	        // DRM
	        // Netflix, Udemy, Spotify, etc.
	        user_pref("media.eme.enabled", true);
	        
	        /** HTTPS-ONLY MODE ***/
	        user_pref("dom.security.https_only_mode_error_page_user_suggestions", true);
	        
	        /** PASSWORDS AND AUTOFILL ***/
	        user_pref("signon.generation.enabled", false);
	        
	        /** WEBRTC ***/
	        // Breaks video conferencing
	        user_pref("media.peerconnection.ice.no_host", false);
	        
	        /** PERMISSIONS ***/
	        user_pref("permissions.default.geo", 2);
	        user_pref("permissions.default.desktop-notification", 2);
	        user_pref("dom.push.enabled", false);
	        
	        /****************************************************************************
	         * SECTION: PESKYFOX                                                        *
	        ****************************************************************************/
	        /** MOZILLA UI ***/
	        user_pref("layout.css.prefers-color-scheme.content-override", 2);
	        user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
	        user_pref("browser.compactmode.show", true);
	        
	        /** FULLSCREEN ***/
	        user_pref("full-screen-api.transition-duration.enter", "0 0");
	        user_pref("full-screen-api.transition-duration.leave", "0 0");
	        user_pref("full-screen-api.warning.delay", 0);
	        user_pref("full-screen-api.warning.timeout", 0);
	        
	        /** URL BAR ***/
	        user_pref("browser.urlbar.suggest.engines", false);
	        user_pref("browser.urlbar.suggest.topsites", false);
	        user_pref("browser.urlbar.suggest.calculator", true);
	        user_pref("browser.urlbar.unitConversion.enabled", true);
	        
	        /** AUTOPLAY ***/
	        // Default breaks some video players
	        user_pref("media.autoplay.blocking_policy", 0);
	        
	        /** PASSWORDS ***/
	        user_pref("editor.truncate_user_pastes", false);
	        
	        /** DOWNLOADS ***/
	        user_pref("browser.download.autohideButton", true);
	        
	        /** PDF ***/
	        user_pref("browser.download.open_pdf_attachments_inline", true);
	        
	        /** TAB BEHAVIOR ***/
	        user_pref("browser.tabs.loadBookmarksInTabs", true);
	        user_pref("browser.bookmarks.openInTabClosesMenu", false);
	        user_pref("findbar.highlightAll", true);
	      '';
	    };
	  };
	}
	{
	  programs.qutebrowser = {
		enable = true;
		enableDefaultBindings = false;
		greasemonkey = [
		  (pkgs.writeText "youtube_adblock.js" (lib.readFile inputs.youtube_adblock.outPath))
		  (pkgs.writeText "reddit_adblock.js" (lib.readFile inputs.reddit_adblock.outPath))
		  (pkgs.writeText "youtube_sponsorblock.js" (lib.readFile inputs.youtube_sponsorblock.outPath))
		  (pkgs.writeText "html_player.js" (lib.readFile inputs.html_player.outPath))
		  (pkgs.writeText "adsbypasser.js" (lib.readFile inputs.adsbypasser.outPath))
		  (pkgs.writeText "torrent_1337.js" (lib.readFile inputs.torrent_1337.outPath))
		  (pkgs.writeText "bypass_all.js" (lib.readFile inputs.bypass_all.outPath))
	
		  (pkgs.writeText "redirect.user.js" ''
			// ==UserScript==
			// @name Redirect Script
			// @namespace https://example.com
			// @version 1.0
			// @description Redirects URLs by replacing values from config
			// @match *://*/*
			// @run-at document-start
			// @grant none
			// ==/UserScript==
			
			(function() {
			    'use strict';
			
			    var currentUrl = window.location.href;
			    var config = {
			//      'from': 'to',
			        // '^(?:https?://)(?:www.)?youtube.com/shorts/': 'https://yewtu.be/watch?v=',
			        // '^(?:https?://)(?:www.)?youtube.com': 'https://yewtu.be',
			        '^(?:https?://)(?:www.)?reddit.com': 'http://test.local:9999',
			        '^(?:https?://)(?:www.)?old.reddit.com': 'http://test.local:9999',
			    };
			    
			    for (var oldValue in config) {
			        var newValue = config[oldValue];
			        var regex = new RegExp(oldValue, 'g');
			        currentUrl = currentUrl.replace(regex, newValue);
			    }
			    
			    if (currentUrl !== window.location.href) {
			        window.location.href = currentUrl;
			    }
			})();
		  '')
		];
	
		quickmarks = {
		  nixpkgs = "https://github.com/NixOS/nixpkgs";
		  home-manager = "https://github.com/nix-community/home-manager";
		  hackernews = "https://news.ycombinator.com/";
		};
		searchEngines = {
		  DEFAULT = "https://search.brave.com/search?q={}";
		  w = "https://en.wikipedia.org/wiki/Special:Search?search={}&go=Go&ns0=1";
		  aw = "https://wiki.archlinux.org/?search={}";
		  nw = "https://wiki.nixos.org/w/index.php?search={}";
		  g = "https://www.google.com/search?hl=en&q={}";
		  "7x" = "https://1337x.to/search/{}/1/";
		  ddg = "https://duckduckgo.com/?q={}";
		  gh = "https://github.com/search?q={}";
		  imdb = "https://www.imdb.com/find?q={}";
		  yt = "https://www.youtube.com/results?search_query={}";
		  nixpkgs = "https://search.nixos.org/packages?channel=unstable&from=0&size=10&sort=relevance&type=packages&query={}";
		  nixopts = "https://search.nixos.org/options?channel=unstable&size=10&sort=relevance&type=packages&query={}";
		  homeopts = "https://home-manager-options.extranix.com/?query={}&release=master";
		  reddit = "http://test.local:9999/r/{}";
		};
	
		settings = {
		  # tabs.tabs_are_windows = true;
		  editor.command = ["emacsclient" "-c" "{file}"];
		  tabs.title.format = "{audio}{current_title}";
		  completion.open_categories = ["searchengines" "quickmarks" "bookmarks" "history" "filesystem"];
		  auto_save.session = true;
		  colors.webpage.preferred_color_scheme = "dark";
		  colors.webpage.darkmode.enabled = true;
		  colors.webpage.darkmode.algorithm = "lightness-cielab";
		  colors.webpage.darkmode.policy.images = "never";
		  tabs.position = "left";
	
		  # content.canvas_reading = false;
		  # content.geolocation = false;
		  content.blocking.enabled = true;
		  content.pdfjs = false;
		  # content.private_browsing = true; # flush all
		  content.webrtc_ip_handling_policy = "default-public-interface-only";
	
		  fonts.web.size.default = lib.mkForce 18;
	
		  completion.height = "30%";
		  completion.show = "always";
		  completion.shrink = true;
		  prompt.radius = 20;
	
		  # hints.chars = "asdfghjkl";
		  hints.radius = 10;
		  hints.uppercase = true;
	
		  statusbar.position = "bottom";
		  statusbar.show = "never";
		  statusbar.widgets = ["keypress" "search_match" "url" "scroll" "tabs"];
	
		  url.default_page = "about:blank";
		  url.open_base_url = true;
	
		  content.blocking.method = "both";
		  content.blocking.adblock.lists = [
			"https://easylist.to/easylist/easylist.txt"
			"https://easylist.to/easylist/easyprivacy.txt"
			"https://easylist-downloads.adblockplus.org/indianlist.txt"
			"https://raw.githubusercontent.com/gijsdev/ublock-hide-yt-shorts/master/list.txt"
			"https://gitflic.ru/project/magnolia1234/bypass-paywalls-clean-filters/blob/raw?file=bpc-paywall-filter.txt"
			"https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/ultimate.txt"
			"https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/fake.txt"
			"https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/nsfw.txt"
		  ];
	
		  content.user_stylesheets = ["~/.config/qutebrowser/css/block.css" "~/.config/qutebrowser/css/mono.css"];
		};
	
		keyBindings = {
		  normal = {
		    "<Ctrl-c><Ctrl-o>" = "spawn --detach d-stuff {url}";
		    # "<Space>o" = "spawn mpv {url}";
		    "<Ctrl-c><Ctrl-r>" = lib.mkMerge [
		      "config-cycle tabs.show never always"
		      # "config-cycle statusbar.show in-mode always"
		      "config-cycle scrolling.bar never always"
		    ];
		    "<Ctrl-.>" = lib.mkMerge [
		      "config-cycle tabs.show never always"
		      # "config-cycle statusbar.show in-mode always"
		      "config-cycle scrolling.bar never always"
		    ];
		  
		    # Emacs style of bindings; Credits:
		    # https://github.com/qutebrowser/qutebrowser/blob/main/doc/help/configuring.asciidoc#emacs-like-config
		    # https://git.sr.ht/~willvaughn/dots/tree/main/item/.config/qutebrowser/qutemacs.py
		  
		    "<Ctrl-x><Ctrl-r>" = "config-source";
		    "<Alt-m>" = "tab-mute";
		  
		    "tf" = "config-cycle content.user_stylesheets '~/.config/qutebrowser/css/mono.css' ''";
		    "<Ctrl-c>f" = "config-cycle content.user_stylesheets '~/.config/qutebrowser/css/mono.css' ''";
		    "i" = "config-cycle colors.webpage.darkmode.enabled";
		  
		    "<Alt-.>" = "scroll-to-perc";
		    "<Alt-,>" = "scroll-to-perc 0";
		    "b" = "scroll-to-perc 0";
		    "e" = "scroll-to-perc";
		    "<Ctrl-n>" = "scroll down";
		    "<Ctrl-p>" = "scroll up";
		    "<Ctrl-f>" = "scroll right";
		    "<Ctrl-b>" = "scroll left";
		    "<Ctrl-v>" = "scroll-page 0 0.5";
		    "<Alt-v>" = "scroll-page 0 -0.5";
		    "<Ctrl-Shift-v>" = "scroll-page 0 -0.5";
		    "<Alt-n>" = "navigate next";
		    "<Shift-Alt-n>" = "navigate next -t";
		    "<Alt-p>" = "navigate prev";
		    "<Shift-Alt-p>" = "navigate prev -t";
		    "^" = "navigate up";
		    "<Alt-Shift-^>" = "navigate up -t";
		    "<Alt-f>" = "navigate increment";
		    "<Alt-b>" = "navigate decrement";
		    # Address
		    "<Ctrl-x><Ctrl-f>" = "cmd-set-text -s :open -t";
		    "<Ctrl-u><Ctrl-x><Ctrl-f>" = "cmd-set-text -s :open";
		    "<Ctrl-x><Ctrl-v>" = "cmd-set-text :open {url:pretty}";
		    "<Ctrl-u><Ctrl-x><Ctrl-v>" = "cmd-set-text :open -t -r {url:pretty}";
		    "<Ctrl-x><Ctrl-l>" = "cmd-set-text :open {url:pretty}";
		    "<Ctrl-u><Ctrl-x><Ctrl-l>" = "cmd-set-text :open -t -r {url:pretty}";
		  
		    "l" = "back";
		    "r" = "forward";
		    "<Ctrl-x><Left>" = "back";
		    "<Ctrl-x><Right>" = "forward";
		    "g" = "reload";
		    "<Ctrl-u>g" = "reload -f";
		    "<F5>" = "reload";
		    "<Ctrl-F5>" = "reload -f";
		    # Quickmarks
		    "<Ctrl-x>rM" = "quickmark-save";
		    "<Ctrl-x>rq" = "cmd-set-text -s :quickmark-load -t";
		    "<Ctrl-x>rQ" = "cmd-set-text -s :quickmark-load";
		    "<Ctrl-x>rK" = "cmd-set-text -s :quickmark-del";
		    # Bookmarks
		    "<Ctrl-x>rm" = "bookmark-add";
		    "<Ctrl-x>rl" = "bookmark-list -t";
		    "<Ctrl-x>rb" = "cmd-set-text -s :bookmark-load -t";
		    "<Ctrl-x>rB" = "cmd-set-text -s :bookmark-load";
		    "<Ctrl-x>rk" = "cmd-set-text -s :bookmark-del";
		    # Tabs
		    "<Ctrl-x>0" = "tab-close";
		    "<Ctrl-x>k" = "tab-close";
		    "<Ctrl-x><Ctrl-k>" = "tab-close";
		    "<Ctrl-x>1" = "tab-only";
		    "p" = "tab-prev";
		    "P" = "tab-move -";
		    "n" = "tab-next";
		    "N" = "tab-move +";
		    "<Ctrl-x>ta" = "tab-focus 1";
		    "<Ctrl-x>te" = "tab-focus last";
		    "<Ctrl-x>tp" = "tab-pin";
		    "<Ctrl-x>to" = "tab-next";
		    "<Ctrl-x>tO" = "tab-prev";
		    "<Ctrl-x>t1" = "tab-only";
		    "<Ctrl-x>tM" = "tab-move -";
		    "<Ctrl-x>tm" = "tab-move +";
		    "<Ctrl-x>tG" = "cmd-set-text -s :tab-give";
		    "<Ctrl-x>tc" = "tab-clone";
		    "<Ctrl-x>tn" = "cmd-set-text -s :open -t qute://help/index.html";
		    "<Ctrl-x>t<Return>" = "cmd-set-text -s :tab-select";
		    "<Ctrl-x>b" = "cmd-set-text -s :tab-select";
		    "<Ctrl-/>" = "undo";
		    "<Ctrl-x>u" = "undo";
		    "<Alt-1>" = "tab-focus 1";
		    "<Alt-2>" = "tab-focus 2";
		    "<Alt-3>" = "tab-focus 3";
		    "<Alt-4>" = "tab-focus 4";
		    "<Alt-5>" = "tab-focus 5";
		    "<Alt-6>" = "tab-focus 6";
		    "<Alt-7>" = "tab-focus 7";
		    "<Alt-8>" = "tab-focus 8";
		    "<Alt-9>" = "tab-focus -1";
		    "<Ctrl-Alt-p>" = "print";
		    "<Ctrl-x>r<Space>" = "mode-enter set_mark";
		    "<Ctrl-x>rj" = "mode-enter jump_mark";
		    # Windows
		    "<Ctrl-x>5f" = "cmd-set-text -s :open -w";
		    "<Ctrl-x>5p" = "cmd-set-text -s :open -p";
		    "<Ctrl-x>50" = "cmd-set-text -s :close";
		    "<Ctrl-x>5u" = "undo -w";
		    # Zooming
		    "<Ctrl-x>=" = "zoom-in";
		    "<Ctrl-x>-" = "zoom-out";
		    # Copying/Yanking
		    "yD" = "yank domain -s";
		    "yM" = "yank inline [{title}]({url}) -s";
		    "yO" = "yank inline [[{url}][{title}]] -s";
		    "yP" = "yank pretty-url -s";
		    "yT" = "yank title -s";
		    "yY" = "yank -s";
		    "yd" = "yank domain";
		    "ym" = "yank inline [{title}]({url})";
		    "yo" = "yank inline [[{url}][{title}]]";
		    "yp" = "yank pretty-url";
		    "yt" = "yank title";
		    "yy" = "yank";
		    "<Alt-w>" = "yank selection";
		    # Macros
		    "<F3>" = "macro-record";
		    "<F4>" = "macro-run";
		    "<Ctrl-x>(" = "macro-record";
		    "<Ctrl-x>)" = "macro-record";
		    "<Ctrl-x>e" = "macro-run";
		    # Downloads
		    "ad" = "download-cancel";
		    "cd" = "download-clear";
		    # Devtools
		    "wi" = "devtools";
		    "wIf" = "devtools-focus";
		    "wIh" = "devtools left";
		    "wIj" = "devtools bottom";
		    "wIk" = "devtools top";
		    "wIl" = "devtools right";
		    "wIw" = "devtools window";
		  
		    # Miscellaneous
		    "<F11>" = "fullscreen";
		    "<Return>" = "selection-follow";
		    "<Ctrl-Return>" = "selection-follow -t";
		    "<Ctrl-x>z" = "repeat-command";
		    "<Escape>" = "clear-keychain ;; search ;; fullscreen --leave";
		    "<Ctrl-g>" = "clear-keychain ;; search ;; fullscreen --leave";
		    "<Ctrl-c><Ctrl-c>" = "stop";
		    "<Ctrl-c><Alt-w>" = "yank selection";
		    "<back>" = "back";
		    "<forward>" = "forward";
		    "<Ctrl-c>," = "set";
		    "<Ctrl-c>h" = "history";
		    "<Ctrl-x>s" = "session-save";
		    "<Ctrl-x>l" = "session-load";
		    "<Ctrl-h>i" = "help -t";
		  
		    # Change modes
		    # caret
		    "<Ctrl-Space>" = "mode-enter caret";
		    # command
		    "<Alt-x>" = "cmd-set-text :";
		    # hint
		    "<Alt-Space>" = "hint all tab";
		    "<Alt-g>" = "hint";
		    "<Space>" = "hint";
		    "ff" = "hint";
		    "ww" = "hint all tab";
		    "fF" = "hint all tab";
		    "fI" = "hint images tab";
		    "fd" = "hint links download";
		    "fi" = "hint images";
		    "ft" = "hint inputs";
		    "fw" = "hint links yank";
		    "fo" = "hint all spawn --detach d-stuff {hint-url}";
		    "<Ctrl-u><Ctrl-c><Ctrl-o>" = "hint all spawn --detach d-stuff {hint-url}";
		    # insert
		    "<Ctrl-m>" = "mode-enter insert";
		    # passthrough
		    "<Shift-Escape>" = "mode-enter passthrough";
		    "<Ctrl-x><Ctrl-q>" = "mode-enter passthrough";
		    # Quit qutebrowser
		    "<Ctrl-x><Ctrl-c>" = "close";
		    "<Ctrl-u><Ctrl-x><Ctrl-c>" = "quit";
		  
		    "<Ctrl-s>" = "cmd-set-text /";
		    "<Ctrl-r>" = "cmd-set-text ?";
		          
		  };
		  
		    passthrough = {
		    	"<Shift-Escape>" = "mode-leave";
		      "<Ctrl-g>" = "mode-leave";
		  	"<Ctrl-x><Ctrl-q>" = "mode-leave";
		    };
		  
		  
		    command = {
		      # command mode
		      "<Alt-b>" = "rl-backward-word";
		      "<Alt-Backspace>" = "rl-backward-kill-word";
		      "<Alt-d>" = "rl-kill-word";
		      "<Alt-f>" = "rl-forward-word";
		      "<Ctrl-d>" = "rl-delete-char";
		      "<Ctrl-a>" = "rl-beginning-of-line";
		      "<Ctrl-e>" = "rl-end-of-line";
		      "<Ctrl-b>" = "rl-backward-char";
		      "<Ctrl-f" = "rl-forward-char";
		      "<Ctrl-k>" = "rl-kill-line";
		      "<Alt-Delete>" = "rl-filename-rubout";
		      "<Ctrl-w>" = "rl-rubout \" \"";
		      "<Ctrl-Shift-Backspace>" = "rl-unix-line-discard";
		      "<Ctrl-y>" = "rl-yank";
		      "<Alt-w>" = "completion-item-yank";
		      "<Alt-Shift-w>" = "completion-item-yank --sel";
		      "<Shift-Delete>" = "completion-item-del";
		      "<Up>" = "command-history-prev";
		      "<Alt-p>" = "command-history-prev";
		      "<Down>" = "command-history-next";
		      "<Alt-n>" = "command-history-next";
		      "<Shift-Tab>" = "completion-item-focus prev";
		      "<Ctrl-p>" = "completion-item-focus prev";
		      "<Tab>" = "completion-item-focus next";
		      "<Ctrl-n>" = "completion-item-focus next";
		      "<PgDown>" = "completion-item-focus next-page";
		      "<PgUp>" = "completion-item-focus prev-page";
		      "<Ctrl-c><Ctrl-f>" = "completion-item-focus next-category";
		      "<Ctrl-c><Ctrl-b>" = "completion-item-focus prev-category";
		      "<Ctrl-Return>" = "command-accept --rapid";
		      "<Escape>" = "mode-leave";
		      "<Ctrl-g>" = "mode-leave";
		      "<Return>" = "command-accept";
		      "<Ctrl-m>" = "command-accept";
		      "<Ctrl-s>" = "search-next";
		      "<Ctrl-r>" = "search-prev";
		   
		    };
		  
		    insert = {
		      "<Escape>" = "mode-leave";
		      "<Ctrl-g>" = "mode-leave";
		      "<Ctrl-E>" = "edit-text";
		      "<ctrl-f>" = "fake-key <Right>";
		      "<ctrl-b>" = "fake-key <Left>";
		      "<ctrl-a>" = "fake-key <Home>";
		      "<ctrl-e>" = "fake-key <End>";
		      "<ctrl-n>" = "fake-key <Down>";
		      "<ctrl-p>" = "fake-key <Up>";
		      "<alt-f>" = "fake-key <Ctrl-Right>";
		      "<alt-b>" = "fake-key <Ctrl-Left>";
		      "<ctrl-d>" = "fake-key <Delete>";
		      "<alt-d>" = "fake-key <Ctrl-Delete>";
		      "<alt-backspace>" = "fake-key <Ctrl-Backspace>";
		      "<ctrl-w>" = "fake-key <Ctrl-backspace>";
		      "<ctrl-y>" = "insert-text {primary}";
		    };
		  
		    prompt = {
		      # prompt
		      "<Alt-b>" = "rl-backward-word";
		      "<Alt-Backspace>" = "rl-backward-kill-word";
		      "<Alt-d>" = "rl-kill-word";
		      "<Alt-f>" = "rl-forward-word";
		      "<Ctrl-d>" = "rl-delete-char";
		      "<Ctrl-a>" = "rl-beginning-of-line";
		      "<Ctrl-e>" = "rl-end-of-line";
		      "<Ctrl-b>" = "rl-backward-char";
		      "<Ctrl-f>" = "rl-forward-char";
		      "<Ctrl-k>" = "rl-kill-line";
		      "<Alt-Delete>" = "rl-filename-rubout";
		      "<Ctrl-w>" = "rl-rubout \" \"";
		      "<Ctrl-Shift-Backspace>" = "rl-unix-line-discard";
		      "<Ctrl-y>" = "rl-yank";
		      "<Ctrl-p>" = "prompt-item-focus prev";
		      "<Shift-Tab>" = "prompt-item-focus prev";
		      "<Up>" = "prompt-item-focus prev";
		      "<Ctrl-n>" = "prompt-item-focus next";
		      "<Tab>" = "prompt-item-focus next";
		      "<Down>" = "prompt-item-focus next";
		      "<Ctrl-g>" = "mode-leave";
		      "<Escape>" = "mode-leave";
		      "<Ctrl-m>" = "prompt-accept";
		      "<Return>" = "prompt-accept";
		      "<Ctrl-x><Ctrl-p>" = "prompt-open-download --pdfjs";
		      "<Ctrl-x><Ctrl-o>" = "prompt-open-download";
		      "<Alt-e>" = "prompt-fileselect-external";
		      "<Alt-Shift-y>" = "prompt-yank --sel";
		      "<Alt-y>" = "prompt-yank";
		  
		    };
		  
		    register = {
		      "<Ctrl-g>" = "mode-leave";
		      "<Escape>" = "mode-leave";
		  
		    };
		  
		    yesno = {
		      "<Alt-Shift-Y>" = "prompt-yank --sel";
		      "<Alt-Y>" = "prompt-yank";
		      "<Ctrl-g>" = "mode-leave";
		      "<Escape>" = "mode-leave";
		      "<Return>" = "prompt-accept";
		      "N" = "prompt-accept --save no";
		      "Y" = "prompt-accept --save yes";
		      "n" = "prompt-accept no";
		      "y" = "prompt-accept yes";
		    };
		  
		    hint = {
		      "<Escape>" = "mode-leave";
		      "<Ctrl-g>" = "mode-leave";
		      "<Return>" = "hint-follow";
		      "<Ctrl-m>" = "hint-follow";
		    };
		  
		    caret = {
		      "<Ctrl-Space>" = "selection-toggle";
		      "<Escape>" = "mode-leave";
		      "<Ctrl-g>" = "mode-leave";
		      "<Ctrl-f>" = "move-to-next-char";
		      "<Ctrl-b>" = "move-to-prev-char";
		      "<Ctrl-n>" = "move-to-next-line";
		      "<Ctrl-p>" = "move-to-prev-line";
		      "<Ctrl-a>" = "move-to-start-of-line";
		      "<Ctrl-e>" = "move-to-end-of-line";
		      "<Alt-f>" = "move-to-next-word";
		      "<Alt-b>" = "move-to-prev-word";
		      "<Alt-Shift-{>" = "move-to-end-of-prev-block";
		      "<Alt-Shift-}>" = "move-to-end-of-next-block";
		      "<Alt-w>" = "yank selection";
		    };
		  };
	  };
	}
	{
	  services = {
	    mpd = {
	      enable = true;
	      musicDirectory = config.xdg.userDirs.music;
	      network = {
	        listenAddress = "127.0.0.1";
	        port = 6600;
	        startWhenNeeded = true;
	      };
	      extraConfig = ''
	      audio_output {
	        type            "pipewire"
	        name            "pipewire sound server"
	      }
	      auto_update "yes"
	      bind_to_address "@mpd"
	    '';
	    };
	
		mpd-mpris.enable = true;
	    playerctld.enable = true;
	
	  };
	}
	{
	  programs = {
	    mpv = {
	      enable = true;
	      scripts = with pkgs.mpvScripts; [ mpris manga-reader ];
	
	      bindings = {
	        l = "seek  5";
	        h = "seek -5";
	        k = "seek  30";
	        j = "seek -30";
	        J = "cycle sub";
	        K = "cycle sub down";
	        B = "no-osd add contrast -4; no-osd add brightness 4; show-text 'Black Level: \${brightness}'";
	        N = "no-osd add contrast 4; no-osd add brightness -4; show-text 'Black Level: \${brightness}'";
	        r = ''cycle-values video-rotate "90" "180" "270" "0"'';
	        a = "vf toggle hflip";
			"Alt+x" = "script-binding select/menu";
			s = "cycle_values sub-ass-override force no";
	
	      };
	
	      config = {
	        sub-auto = "fuzzy";
	        msg-level = "all=error";
	        ytdl-format = "bestvideo[height<1080]+bestaudio/best";
	        # ytdl-format = "bestvideo";
	        save-position-on-quit = true;
			keep-open = true;
			scale-antiring = "0.6";
			dither-depth = "8";
	        slang = "eng,en,eng,english";
	        alang = "jp,jpn,en,eng";
	        sub-font = lib.mkForce "Gandhi Sans";
	        sub-font-size = "50";
	        speed = "1.5";
			sub-ass-override = "no";
			sub-ass-style-overrides = "playresx=1440,playresy=900,Kerning=yes";
			sub-color = "#FFFFFF";
			sub-margin-y = "40";
			sub-border-size = "2.4";
			sub-border-color = "#FF000000";
			sub-shadow-color = "#A0000000";
			sub-shadow-offset = "0.75";
			sub-bold = "yes";
	      };
	    };
	  };
	}
	{
	  programs = {
	    yt-dlp = {
	      enable = true;
	      settings = {
	        embed-thumbnail = true;
	        embed-metadata = true;
	        embed-subs = true;
	        sub-langs = "en";
	      };
	    };
	  };
	}
	{
	  programs.swayimg = {
	    enable = true;
	    settings = {
	      viewer = {
	        window = "#00000000";
	        scale = "fit";
	      };
	        "keys.viewer" = {
	          "F1" = "help";
	          "Ctrl+h" = "help";
	          "Ctrl+a" = "first_file";
	          "Ctrl+e" = "last_file";
	          "p" = "prev_file";
	          "n" = "next_file";
	          "Space" = "next_file";
	          "Shift+d" = "prev_dir";
	          "d" = "next_dir";
	          "Shift+o" = "prev_frame";
	          "o" = "next_frame";
	          "c" = "skip_file";
	          "F5" = "slideshow";
	          "s" = "animation";
	          "f" = "fullscreen";
	          "Return" = "mode";
	          "h" = "step_left 10";
	          "l" = "step_right 10";
	          "k" = "step_up 10";
	          "j" = "step_down 10";
	          "Equal" = "zoom +10";
	          "Plus" = "zoom +10";
	          "Minus" = "zoom -10";
	          "Shift+w" = "zoom width";
	          "Shift+h" = "zoom height";
	          "bracketleft" = "rotate_left";
	          "bracketright" = "rotate_right";
	          "r" = "rotate_right";
	          "Shift+r" = "rotate_left";
	          "Shift+Delete" = "exec rm -f '%' && echo 'File removed: %'; skip_file";
	          "m" = "flip_vertical";
	          "Shift+m" = "flip_horizontal";
	          "q" = "exit";
	        };
	    };
	  };
	}
	
	{
	  home.packages = with pkgs; [
	    # screenshot
	    grim slurp nautilus
		libreoffice-fresh
	
	    libnotify libsixel
	    brightnessctl
	    wtype gtk3
	    swaybg swayimg swayidle wlsunset
	
	    wl-screenrec wl-mirror
	    wl-clipboard-rs xwayland-satellite
	    mupdf poppler-utils ghostscript # for doc-view
	    uv prettier
	
	    pavucontrol pulsemixer playerctl
	    transmission_4-gtk
	
	    mpc ani-cli
	  ];
	}
	{
	  services.hypridle = let
	    hyprlock = lib.getExe pkgs.hyprlock;
		noctalia = lib.getExe inputs.noctalia.packages.x86_64-linux.default;
	    brightness = lib.getExe pkgs.brightnessctl;
	    niri = lib.getExe pkgs.niri;
	    timeout = 200; # base timer to act upon
	    in {
	    enable = true;
	    settings ={
	      general = {
	        lock_cmd = "${noctalia} ipc call lockScreen lock";
	        before_sleep_cmd = "${pkgs.systemd}/bin/loginctl lock-session";
	        unlock_cmd = "notify-send 'Welcome back!'";
	      };
	
	      listener = [
	        {
	          timeout = timeout - 50;
	          on-timeout = "${brightness} -s set 5%";
	          on-resume = "${brightness} -r";
	        }
	        {
	          timeout = timeout;
	          on-timeout = "loginctl lock-session";
	        }
	        {
	          timeout = timeout + 10;
	          on-timeout = "${niri} msg action power-off-monitors";
	          on-resume = "${niri} msg action power-on-monitors";
	        }
	        {
	          timeout = timeout * 5;
	          on-timeout = "systemctl suspend";
	        }
	      ];
	    };
	  };
	}
	{
	  stylix = {
	    enable = true;
	
	    iconTheme = { # watch out soon stylix might implement this
	      enable = true;
	      dark = "Papirus-Dark";
	      package = pkgs.papirus-icon-theme;
	    };
	
	    targets = {
	      emacs.enable = false;
	      librewolf.profileNames = [ "ihome" ];
	      gtk.extraCss = ''
	            @define-color light_1 #ffffff;
	            @define-color dark_5 #000000;
	      '';
	    };
	  };
	}
	inputs.vicinae.homeManagerModules.default
	{
	  services.vicinae = {
	    enable = true;
	    autoStart = true;
	  };
	}
	{
	  programs = {
	    eza = {
	      enable = true;
	      extraOptions = ["--group-directories-first" "--header"];
	    };
	
	    ripgrep = {
	      enable = true;
	      arguments = [
	        "--max-columns-preview"
	        # "--colors=line:style:bold"
	        "--ignore-case"
	        "--follow"
	        "--null" "--line-buffered" "--max-columns=1000" "--smart-case" "--no-heading" "--with-filename" "--line-number"
	      ];
	    };
	
	    btop = {
	      enable = true;
	      settings = {
	        # color_theme = "default";
	        theme_background = false;
	        vim_keys = true;
	        shown_boxes = "proc cpu";
	        rounded_corners = true ;
	        graph_symbol = "block";
	        proc_sorting = "memory";
	        proc_reversed = false;
	        proc_gradient = true;
	      };
	    };
	
	    bat = {
	      enable = true;
	      extraPackages = with pkgs.bat-extras; [ batdiff batman batgrep batwatch ];
	    };
	
	    ssh = {
	      enable = true;
		  enableDefaultConfig = true;
	      extraOptionOverrides = {
	        SetEnv = "TERM=xterm-256color";
	      };
	      matchBlocks."172.16.2.72" = {
	        forwardX11Trusted = true;
	        forwardX11 = true;
	      };
	
	      };
	
	    fzf = {
	      enable = true;
	      defaultCommand = "fd --type f";
	    };
	
	  };
	}
	{
	  home = {
	    sessionVariables = {
	      EDITOR = "emacsclient -c";
	      VISUAL = "$EDITOR";
	      GRIM_DEFAULT_DIR = "$HOME/pics/sshots/";
	      STARDICT_DATA_DIR = "$HOME/d-git/d-bin/treasure/dict/";
	      LESS = "-J -i -W --status-line --incsearch --use-color -R";
	      COLORTERM="truecolor";
	    };
	    sessionPath = [ "$HOME/.local/bin" "$HOME/.bin" ];
	    keyboard.options = [ "ctrl:nocaps" ];
	    preferXdgDirectories = true;
	
	    shellAliases = {
	      cleanup = "doas nix-collect-garbage --delete-older-than 7d";
	      bloat = "nix path-info -Sh /run/current-system";
	      ytmp3 = "yt-dlp -x --continue --add-metadata --embed-thumbnail --audio-format mp3 --audio-quality 0 --metadata-from-title = '%(artist)s - %(title)s' --prefer-ffmpeg -o '%(title)s.%(ext)s' ";
	      cat = "bat";
	      grep = "rg";
	      du = "dust";
	      ls = "eza -h --git --icons --color=auto --group-directories-first -s extension";
	      l = "ls -lF --time-style=long-iso --icons";
	      la = "eza -lah --tree";
	      tree = "eza --tree --icons";
	      http = "python3 -m http.server";
	      burn = "pkill -9";
	      diff = "diff --color=auto";
	      ".1" = "cd ..";
	      ".2" = "cd ../..";
	      ".3" = "cd ../../..";
	      c = "clear";
	      v = "emacsclient -nw";
	      e = "emacsclient -nw";
	      emd = "emacs --daemon";
	      cp = "cp -iv";
	      mv = "mv -iv";
	      rm = "rm -vI";
	      bc = "bc -ql";
	      mkd = "mkdir -pv";
	      gc = "git clone --depth=1";
	      sioyek = "sioyek --new-window";
	      hyprunlock = "pkill -SIGUSR1 hyprlock";
	      rebuild = "nixos-rebuild switch --flake ~/d-git/d-nix#host ";
	      testrebuild = "nixos-rebuild test --flake ~/d-git/d-nix#host";
	      ytdl = "yt-dlp --embed-metadata --embed-subs";
	      fcd = "cd $(fd -t d | fzf)";
	      open = "emacsclient -t $(fd -t f | fzf)";
	    };
	
	  };
	
	}
	{
	  home.packages = with pkgs; [
	    zip unzip # archives
	    ffmpeg-full sdcv nq
	    # utils
	    dust fd wget ripgrep-all file
	  ];
	}
	{
	  programs.starship = {
	    enable = true;
	     settings = {
	      add_newline = true;
	      scan_timeout = 5;
	
	      line_break.disabled = false;
	
	      character = {
	        success_symbol = " ";
	        error_symbol = "󰘧";
	      };
	
	      hostname = {
		      ssh_only = true;
		      format = "[$hostname](bold blue) ";
		      disabled = false;
	      };
	    };
	  };
	}
	{
	  programs = {
	    fish = {
	    enable = true;
	    };
	    bash = {
	      enable = true;
	    };
	  };
	}
	{
	  home.packages = with pkgs; [
	    # texlive.combined.scheme-full
	    typst ollama
	  ];
	}
	{
	  programs.aria2 = {
	    enable = true;
	    settings = {
	      dir = config.xdg.userDirs.download;
	      file-allocation = "none";
	      log-level = "warn";
	      split = "10";
	      max-connection-per-server = 10;
	      min-split-size = "5m";
	      bt-max-peers = "0";
	      bt-request-peer-speed-limit = "0";
	      max-overall-upload-limit = "512k";
	      bt-external-ip = "127.0.0.1";
	      dht-listen-port = "6882";
	      enable-dht = "true";
	      enable-peer-exchange = "true";
	      listen-port = "6881";
	      bt-force-encryption = "true";
	      bt-min-crypto-level = "arc4";
	      bt-require-crypto = "true";
	      follow-torrent = "mem";
	      seed-ratio = "100";
	      seed-time = "0";
	      socket-recv-buffer-size = "1m";
	      event-poll = "epoll";
	      realtime-chunk-checksum = "true";
	      allow-overwrite = "true";
	      always-resume = "true";
	      auto-file-renaming = "false";
	      continue = "true";
	      rpc-save-upload-metadata = "false";
	    };
	  };
	}
	{
	  programs.rofi = {
	    enable = true;
		plugins = with pkgs; [ rofi-nerdy rofi-calc rofi-emoji ];
		modes = [ "drun" "run" "window" "calc" "nerdy" "emoji" ];
	    extraConfig = {
	      modi = "drun,run,window,combi";
		  combi-modes = [ "window" "drun" "run" "nerdy" "emoji" ];
	      show-icons = true;
	      hide-scrollbar = true;
	      display-drun = " Apps ";
	      display-run = "  Run ";
	      display-window = "󰍲   Window ";
	      sidebar-mode = true;
	      drun-show-actions = true;
	    };
		theme = {
		  "@import" = "dmenu";
		};
	  };
	}
	{ home.packages = with pkgs; [ libnotify nemo pandoc groff mupdf keepassxc easyeffects jaq
	  #libreoffice-fresh
	]; }
	{
	
	  home = with pkgs;
	    let
	      mySpells = aspellWithDicts (dicts: with dicts; [ en en-computers ]);
	    in
	      {
	        file.".aspell.conf".text = ''
	          dict-dir ${mySpells}/lib/aspell/
	          add-extra-dicts en-computers.rws
	        '';
	        packages = [
	          # languagetool
	          mySpells
	          hunspell hunspellDicts.en_US-large hunspellDicts.en_GB-large
	        ];
	      };
	}
  ];

  # NEVER EVER TOUCH IT ⚠️
  home.stateVersion = "25.05"; # refer manual !

  # home configuration ends here
}
