{ config, lib, pkgs, inputs, modulesPath, vars, ...}:
{
  # WARNING : This file was generated by d-setup.org
  # DO NOT MODIFY THIS FILE!
  # Any changes made here will be overwritten.

  imports = [
  {
    home-manager = {
      useUserPackages = true;
      useGlobalPkgs = true;
      extraSpecialArgs = {
        inherit inputs vars;
      };
      users.${vars.username} = import ./home.nix;
    };
  }
  {
    boot = {
      # Uses bleeding edge latest kernel.
      kernelPackages = pkgs.linuxPackages_latest;
      loader = {
        systemd-boot.enable = true;
        efi.canTouchEfiVariables = true; # maybe for dualboot
      };
      initrd.availableKernelModules = [
        "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci"
      ];
  
      supportedFilesystems = [ "ntfs" ];
      tmp.cleanOnBoot = true;
  	enableContainers = true;
  
      kernelParams = [
        "systemd.mask=dev-tpmrm0.device" #this is to mask that stupid 1.5 mins systemd bug
        "nowatchdog" "modprobe.blacklist=iTCO_wdt" #watchdog for Intel
   	  ];
    };
  }
  # Do not modify this file!  It was generated by ‘nixos-generate-config’
  # and may be overwritten by future invocations.  Please make changes
  # to /etc/nixos/configuration.nix instead.
  {
    imports =
      [ (modulesPath + "/installer/scan/not-detected.nix")
      ];
  
    boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "vmd" "nvme" "usbhid" "usb_storage" "sd_mod" ];
    boot.kernelModules = [ "kvm-intel" "i2c-dev" "ddcci_backlight" ];
    boot.extraModulePackages = [ config.boot.kernelPackages.ddcci-driver ];
    boot.initrd.kernelModules = [ "dm-snapshot" ];
  
    fileSystems."/" = {
        fsType = "btrfs";
        options = [ "subvol=root" "compress=zstd" ];
      };
  
    fileSystems."/home" = { 
        fsType = "btrfs";
        options = [ "subvol=home" "compress=zstd" ];
      };
  
    fileSystems."/nix" = { 
        fsType = "btrfs";
        options = [ "subvol=nix" "compress=zstd" "noatime" ];
      };
  
    fileSystems."/boot" = { 
        fsType = "vfat";
        options = [ "fmask=0022" "dmask=0022" ];
      };
  
    swapDevices = [ ];
  
    # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
    # (the default) this is the recommended approach. When using systemd-networkd it's
    # still possible to use this option, but it's recommended to use it in conjunction
    # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
    networking.useDHCP = lib.mkDefault true;
    # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;
  
    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  }
  {
    time = {
      timeZone = "Asia/Kolkata";
    };
  }
  {
    users.users.${vars.username} = {
      isNormalUser = true;
      shell = pkgs.fish;
      extraGroups = ["adbusers" "input" "uinput" "libvirtd" "networkmanager" "plugdev" "transmission" "video" "wheel" "docker" "i2c"];
    };
  }
  { zramSwap.enable = true; }
  {
    systemd.sleep.extraConfig = ''
     AllowSuspend=yes
     '';
    # Avoid long stop job (easyeffects)
    systemd.user.extraConfig = ''DefaultTimeoutStopSec=10s'';
    systemd.settings.Manager = {
  	DefaultTimeoutStopSec = "10s";
    };
  }
  { # remap caps to control
    services.udev.extraHwdb = ''
    evdev:atkbd:*
     KEYBOARD_KEY_3a=leftctrl
    '';
  }
  {
    networking = {
      hostName = "${vars.host}";
  
  	hosts = {
  	  "127.0.0.1" = [ "test.local" "foss.local" ];
  	};
  
      # Killer feature, Its a must these days.
      # Adblocker!! It uses hagezi dns-blocklist
      hostFiles = [
  	  inputs.dns-block
  	  inputs.dns-tif
        inputs.dns-bpc
      ];
  
      nameservers = [ "9.9.9.9" "1.1.1.1" ];
  
      networkmanager = {
        enable = true;
        unmanaged = ["docker0" "rndis0" "interface-name:ve-*" ];
        wifi.macAddress = "random"; # randomness? whitelist?
      };
  
      # Firewall uses iptables underthehood
      # Rules are for syncthing & kdeconnect
      firewall = rec {
        enable = true;
        allowedTCPPortRanges = [ { from = 1714; to = 1764; } ];
        allowedUDPPortRanges = allowedTCPPortRanges;
        allowedTCPPorts = [8384 22000 80 8000 53 5300 8080 8081];
        allowedUDPPorts = [22000 21027 53 5300];
      };
  
      nat = { # for container or vm
        enable = true;
        internalInterfaces = ["ve-+"];
        externalInterface = "wlp0s20f3";
        # Lazy IPv6 connectivity for the container
        enableIPv6 = true;
      };
  
    };
  }
  {
    services = {
      openssh = { # ssh
        enable = true;
        settings = {
          UseDns = true;
          SetEnv = "TERM=xterm";
          };
      };
  	resolved.enable = true;
    };
  }
  {
    # this makes our system more secure
    # note that it might break some stuff, eg webcam
  
    security = {
      rtkit.enable = true;
      polkit.enable = true;
  
      doas = {
        enable = true;
        extraRules = [{
          users = [ "${vars.username}" ];
          keepEnv = true;
          persist = true;
        }];
      };
  
      sudo.enable = false;
    };
  }
  {
    environment = {
      variables = {
        BROWSER = "d-stuff";
        NIXOS_OZONE_WL = "1";
      };
      pathsToLink = [ "/share/xdg-desktop-portal" "/share/applications" ];
      systemPackages = with pkgs; [
        gitFull
        (writeScriptBin "sudo" ''exec doas "$@"'')
      ];
    };
  }
  {
    services = {
      getty = {
        greetingLine = "Greetings and Welcome back!";
        helpLine = "Let's learn more and get productive!";
      };
      atd.enable = true; # reminder tool, like @ 2:30 | exec this
    };
  }
  { # For android file transfer via usb, or better could use KDE connect
    services.gvfs.enable = true;
  }
  {
    # For Laptop, make lid close and power buttom click to suspend
    services.logind.settings.Login = {
      HandleLidSwitch = "suspend";
      HandlePowerKey = "suspend";
    };
  }
  { # for fingerprint
    services.fprintd.enable = true;
  }
  {
    services.hardware.bolt.enable = true;
  }
  {
    services = {
  	power-profiles-daemon.enable = true;
  	upower.enable = true;
  	};
  }
  {
    services.thermald.enable = true;
  }
  {
    services = { # To mount drives with `udiskctl` command
      udisks2.enable = true;
      # printing.enable = true;
    };
  }
  {
    environment = {
      # set channels (backwards compatibility)
      etc = {
        "nix/flake-channels/nixpkgs".source = inputs.nixpkgs;
        "nix/flake-channels/home-manager".source = inputs.home-manager;
      };
    };
  }
  {
    nixpkgs = {
  	overlays = [ (import inputs.emacs-overlay) ];
    };
    nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
      "steam-unwrapped"
    ];
  }
  {
    nix = {
  	package = pkgs.nixVersions.latest;
      # pin the registry to avoid downloading and evaling a new nixpkgs version every time
      registry = lib.mapAttrs (_: value: { flake = value; }) inputs;
  
      # This will additionally add your inputs to the system's legacy channels
      # Making legacy nix commands consistent as well, awesome!
      nixPath = lib.mapAttrsToList (key: value: "${key}=${value.to.path}") config.nix.registry;
  
      settings = {
        flake-registry = "/etc/nix/registry.json";
        extra-experimental-features = ["flakes" "nix-command" ];
        warn-dirty = false;
  
        # use binary cache, its not gentoo
  	  trusted-users = [ "root" "dev" "idlip" ];
  	  # extra-substituters = [ "https://vicinae.cachix.org" ];
  	  # extra-trusted-public-keys = [ "vicinae.cachix.org-1:1kDrfienkGHPYbkpNj1mWTr7Fm1+zcenzgTizIcI3oc=" ];
        substituters = [ "https://nix-community.cachix.org" ];
        trusted-public-keys = [ "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=" ];
      };
    };
  }
  {
    programs.nix-index-database.comma.enable = true;
    programs.nix-index.enable = true;
  }
  { programs.nix-ld.enable = true; }
  {
    programs.nh = {
      enable = true;
      flake = "/home/${vars.username}/d-git/d-nix";
    };
  }
  { # disable for faster rebuilding
    documentation = {
      enable = true;
      doc.enable = true;
      info.enable = true;
      man = {
        enable = true;
        generateCaches = true; # will take little time
      };
      dev.enable = true;
    };
  }
  {
    programs.fish.enable = true;
  }
  {
    hardware = {
      uinput.enable = true;
      i2c.enable = true;
      graphics = {
        enable = true;
        enable32Bit = true;
        extraPackages = with pkgs; [ intel-media-driver intel-vaapi-driver libvdpau-va-gl mesa vulkan-loader vulkan-tools ];
        extraPackages32 = with pkgs.pkgsi686Linux; [
          vulkan-loader                        # Vulkan runtime (32-bit).
          driversi686Linux.mesa                # 32-bit Vulkan drivers for AMD/Intel.
          driversi686Linux.intel-media-driver  # Intel 32-bit media driver.
        ];
  
      };
    };
  }
  {
    services.pipewire = {
      enable = true;
      alsa = {
        enable = true;
        support32Bit = true;
      };
      wireplumber.enable = true;
      pulse.enable = true;
      jack.enable = true;
    };
  }
  {
    hardware.bluetooth = {
      enable = true;
    };
    services.blueman.enable = true;
  }
  {
    services.syncthing = {
      enable = true;
      user = "${vars.username}";
      configDir = "/home/${vars.username}/.config/syncthing";
      dataDir = "/home/${vars.username}/.local/share/syncthing";
      overrideDevices = true;     # overrides any devices added or deleted through the WebUI
      overrideFolders = true;     # overrides any folders added or deleted through the WebUI
      settings = let
        device_name = "dphone";
  	  laptop_id = if vars.host == "foss"
  	  then "OMS7TLF-KFUSQ6I-ISR6HXQ-M6UPTZR-LCL43BE-4IBELWZ-ZEX4AYK-Z6YEXA7"
  	  else "5GKACFD-GVRTVC2-4GYGS3L-P6BHGT4-47DAE5U-GJL2SOX-545KJTX-AVZQ5QP";
        in {
        devices = {
          "${device_name}" = { id = "CLVZ4YX-RS5G23W-4Y7TGV4-6P7G6DP-VNYUWIP-MQQGZXC-NCH56MN-O3FMAA5"; };
          "laptop" = { id = laptop_id; };
        };
        folders = {
          "sync" = {
  	        path = "~/d-sync";
  	        devices = [ device_name "laptop" ];
          };
          "emacs" = {
  	        path = "~/d-git/d-nix";
  	        devices = [ device_name "laptop" ];
          };
        };
      };
    };
  }
  {
    programs = {
      niri.enable = true;
      };
  }
  {
    programs.hyprlock.enable = true; # for pam auth config
  }
  {
    programs.mango.enable = true;
  }
  {
    fonts = {
      packages = with pkgs; [
        noto-fonts noto-fonts-color-emoji
        material-symbols material-icons
      ];
      enableDefaultPackages = true;
    };
  }
  {
    stylix = {
      enable = true;
      image = ./configs/chinese-dragon.jpg;
      polarity = "dark";
  
      base16Scheme = "${pkgs.base16-schemes}/share/themes/bright.yaml";
  
      cursor = {
        package = pkgs.maplestory-cursor;
        name = "Maple";
        size = 24;
      };
  
      fonts = let
        dpkg = (pkgs.callPackage ./pkgs/code-d-font.nix {});
  
        plexpkg = pkgs.ibm-plex;
        ipkg = pkgs.inter;
  
        mpkg = pkgs.maple-mono.NF;
        apkg = pkgs.aporetic-bin;
  
      in {
        serif = {
          package = plexpkg;
          name = "IBM Plex Serif";
        };
  
        sansSerif = {
          package = ipkg;
          name = "Inter";
        };
  
        monospace = {
          package = mpkg;
          name = "Maple Mono NF";
        };
  
        emoji = {
          package = pkgs.noto-fonts-color-emoji;
          name = "Noto Color Emoji";
        };
  
        sizes = {
          applications = 12;
          desktop = 12;
          popups = 12;
          terminal = 12;
        };
  
      };
    };
  
  }
  {
    boot.initrd.luks.devices.cryptroot.device = "/dev/disk/by-uuid/ad2f4bf9-01eb-4c84-9a94-ba122aee88df";
    fileSystems."/" = { device = "/dev/disk/by-uuid/a367f747-513c-4bc9-a389-36ffbc182f7e"; };
    fileSystems."/home" = { device = "/dev/disk/by-uuid/a367f747-513c-4bc9-a389-36ffbc182f7e"; };
    fileSystems."/nix" = { device = "/dev/disk/by-uuid/a367f747-513c-4bc9-a389-36ffbc182f7e"; };
    fileSystems."/boot" = { device = "/dev/disk/by-uuid/112B-98A0"; };
  }
  {
	stylix.base16Scheme = lib.mkForce "${pkgs.base16-schemes}/share/themes/kanagawa.yaml";
  }
  {	
	services.throttled.enable = true;
  }

	{
	  virtualisation.docker = {
		enable = true;
		storageDriver = "btrfs";
		# Customize Docker daemon settings using the daemon.settings option
		daemon.settings = {
		  dns = [ "1.1.1.1" "9.9.9.9" ];
		  log-driver = "journald";
		  registry-mirrors = [ "https://mirror.gcr.io" ];
		};
	  };
	}
  ];

  # stateVersion
  # NEVER EVER TOUCH THIS ⚠️
  system.stateVersion = lib.mkDefault "25.05"; # refer manual !

}
