{ config, lib, pkgs, inputs, modulesPath, vars, ...}:
{
  # WARNING : This file was generated by d-setup.org
  # DO NOT MODIFY THIS FILE!
  # Any changes made here will be overwritten.

  imports = [
  {}
  {
    home-manager = {
      useUserPackages = true;
      useGlobalPkgs = true;
      extraSpecialArgs = {
        inherit inputs vars;
      };
      users.${vars.username} = import ./home.nix;
    };
  }
  
  {
    boot = {
      # Uses bleeding edge latest kernel.
      kernelPackages = pkgs.linuxPackages_latest;
      loader = {
        systemd-boot.enable = true;
        efi.canTouchEfiVariables = true; # maybe for dualboot
      };
      initrd.availableKernelModules = [
        "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci"
      ];
  
      supportedFilesystems = [ "ntfs" ];
      tmp.cleanOnBoot = true;
  
      kernelParams = [
        "systemd.mask=dev-tpmrm0.device" #this is to mask that stupid 1.5 mins systemd bug
        "nowatchdog" "modprobe.blacklist=iTCO_wdt" #watchdog for Intel
   	  ];
    };
  }
  
  {
    time = {
      timeZone = "Asia/Kolkata";
    };
  }
  {
    users.users.${vars.username} = {
      isNormalUser = true;
      shell = pkgs.fish;
      extraGroups = ["adbusers" "input" "uinput" "libvirtd" "networkmanager" "plugdev" "transmission" "video" "wheel"];
    };
  }
  { zramSwap.enable = true; }
  {
    systemd.sleep.extraConfig = ''
     AllowSuspend=yes
     '';
  }
  
  {
    networking = {
      hostName = "gdk";
  
  	hosts = {
  	  "127.0.0.1" = [ "test.local" "foss.local" ];
  	};
  
      # Killer feature, Its a must these days.
      # Adblocker!! It uses hagezi dns-blocklist
      hostFiles = [
        (pkgs.fetchurl {
          url = "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/ultimate-compressed.txt";
          hash = "sha256-FrbQF7XmAFl5WzmqSarSMTLcNHU6ZUiejcr5sQ2a5hs=";
        })
        (pkgs.fetchurl {
          url = "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/hosts/tif-compressed.txt";
          hash = "sha256-v1248nwoLuI8kbq+N9nZKFpdPUYPqgSCJvauKmyvwXo=";
        })
  
      ];
  
      nameservers = [ "9.9.9.9" "1.1.1.1" ];
  
      networkmanager = {
        enable = true;
        unmanaged = ["docker0" "rndis0" "interface-name:ve-*" ];
        wifi.macAddress = "random"; # randomness? whitelist?
      };
  
      # Firewall uses iptables underthehood
      # Rules are for syncthing & kdeconnect
      firewall = rec {
        enable = true;
        allowedTCPPortRanges = [ { from = 1714; to = 1764; } ];
        allowedUDPPortRanges = allowedTCPPortRanges;
        allowedTCPPorts = [8384 22000];
        allowedUDPPorts = [22000 21027];
      };
  
      nat = { # for container or vm
        enable = true;
        internalInterfaces = ["ve-+"];
        externalInterface = "wlp0s20f3";
        # Lazy IPv6 connectivity for the container
        enableIPv6 = true;
      };
  
    };
  }
  {
    services = {
      openssh = { # ssh
        enable = true;
        settings = {
          UseDns = true;
          SetEnv = "TERM=xterm";
          };
      };
  	resolved.enable = true;
    };
  }
  
  {
    # this makes our system more secure
    # note that it might break some stuff, eg webcam
  
    security = {
      rtkit.enable = true;
      polkit.enable = true;
  
      doas = {
        enable = true;
        extraRules = [{
          users = [ "${vars.username}" ];
          keepEnv = true;
          persist = true;
        }];
      };
  
      sudo.enable = false;
    };
  }
  
  {
    services = {
      getty = {
        greetingLine = "Greetings and Welcome back!";
        helpLine = "Let's learn more and get productive!";
      };
      atd.enable = true; # reminder tool, like @ 2:30 | exec this
    };
  }
  { # For android file transfer via usb, or better could use KDE connect
    services.gvfs.enable = true;
    adb.enable = true; # help manage android devices via command#  line
  }
  {
    # For Laptop, make lid close and power buttom click to suspend
    services.logind = {
      lidSwitch = "suspend";
      powerKey = "suspend";
    };
  }
  {
    services.hardware.bolt.enable = true;
  }
  {
    services.power-profiles-daemon.enable = true;
  }
  {
    services.thermald.enable = true;
  }
  {
    services = { # To mount drives with `udiskctl` command
      udisks2.enable = true;
      # printing.enable = true;
    };
  }
  
  {
    environment = {
      variables = {
        BROWSER = "d-stuff";
        NIXOS_OZONE_WL = "1";
      };
      pathsToLink = [ "/share/xdg-desktop-portal" "/share/applications" ];
      systemPackages = with pkgs; [
        gitFull
        (writeScriptBin "sudo" ''exec doas "$@"'')
      ];
    };
  }
  {
    environment = {
      # set channels (backwards compatibility)
      etc = {
        "nix/flake-channels/nixpkgs".source = inputs.nixpkgs;
        "nix/flake-channels/home-manager".source = inputs.home-manager;
      };
    };
  }
  {
    nixpkgs = {
      overlays = with inputs; [emacs-overlay.overlay];
    };
  }
  {
    nix = {
  	package = pkgs.nixVersions.latest;
      # pin the registry to avoid downloading and evaling a new nixpkgs version every time
      registry = lib.mapAttrs (_: value: { flake = value; }) inputs;
  
      # This will additionally add your inputs to the system's legacy channels
      # Making legacy nix commands consistent as well, awesome!
      nixPath = lib.mapAttrsToList (key: value: "${key}=${value.to.path}") config.nix.registry;
  
      settings = {
        flake-registry = "/etc/nix/registry.json";
        extra-experimental-features = ["flakes" "nix-command" ];
        warn-dirty = false;
  
        # use binary cache, its not gentoo
        substituters = [ "https://nix-community.cachix.org" ];
        trusted-public-keys = [ "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=" ];
      };
    };
  }
  {
    programs.nix-index-database.comma.enable = true;
    programs.nix-index.enable = true;
  }
  { programs.nix-ld.enable = true; }
  {
    programs.nh = {
      enable = true;
      flake = "/home/${vars.username}/d-git/d-nix";
    };
  }
  
  { # disable for faster rebuilding
    documentation = {
      enable = true;
      doc.enable = true;
      info.enable = true;
      man = {
        enable = true;
        generateCaches = true; # will take little time
      };
      dev.enable = true;
    };
  }
  
  {
    hardware = {
      uinput.enable = true;
      graphics = {
        enable = true;
        enable32Bit = true;
        extraPackages = with pkgs; [ intel-media-driver intel-vaapi-driver libvdpau-va-gl mesa vulkan-loader vulkan-tools ];
        extraPackages32 = with pkgs.pkgsi686Linux; [
          vulkan-loader                        # Vulkan runtime (32-bit).
          driversi686Linux.mesa                # 32-bit Vulkan drivers for AMD/Intel.
          driversi686Linux.intel-media-driver  # Intel 32-bit media driver.
        ];
  
      };
    };
  }
  {
    services.pipewire = {
      enable = true;
      alsa = {
        enable = true;
        support32Bit = true;
      };
      wireplumber.enable = true;
      pulse.enable = true;
      jack.enable = true;
    };
  }
  {
    hardware.bluetooth = {
      enable = true;
    };
    services.blueman.enable = true;
  }
  
  {
    programs = {
      niri.enable = true;
      xwayland.enable = true;
      };
  }
  
  {
    programs.hyprlock.enable = true; # for pam auth config
  }
  
  {
    fonts = {
      packages = with pkgs; [
        noto-fonts noto-fonts-emoji unifont
        merriweather atkinson-hyperlegible
        # (iosevka-bin.override { variant = "Aile"; }) nerd-fonts.iosevka
      ];
  
      enableDefaultPackages = true;
    };
  }
  
  {
    stylix = {
      enable = true;
      image = ./configs/chinese-dragon.jpg;
      polarity = "dark";
  
      base16Scheme = "${pkgs.base16-schemes}/share/themes/bright.yaml";
  
      cursor = {
        package = pkgs.layan-cursors;
        name = "layan-cursors";
        size = 24;
      };
  
      fonts = let
        dpkg = (pkgs.callPackage ./pkgs/code-d-font.nix {});
  
        plexpkg = pkgs.ibm-plex;
        ipkg = pkgs.inter;
  
        mpkg = pkgs.maple-mono.NF;
        apkg = pkgs.aporetic-bin;
  
      in {
        serif = {
          package = plexpkg;
          name = "IBM Plex Serif";
        };
  
        sansSerif = {
          package = ipkg;
          name = "Inter";
        };
  
        monospace = {
          package = mpkg;
          name = "Maple Mono NF";
        };
  
        emoji = {
          package = pkgs.noto-fonts-emoji;
          name = "Noto Color Emoji";
        };
  
        sizes = {
          applications = 12;
          desktop = 12;
          popups = 12;
          terminal = 12;
        };
  
      };
    };
  
  }
  
  {
    programs.fish.enable = true;
  }
  ];

  # stateVersion
  # NEVER EVER TOUCH THIS ⚠️
  system.stateVersion = lib.mkDefault "25.05"; # refer manual !

}
