{pkgs, lib, config, vars, inputs, ...}:
{
  # WARNING : This file was generated by d-setup.org
  # DO NOT MODIFY THIS FILE!
  # Any changes made here will be overwritten.

  imports = [
	{
	   services = {
	    gpg-agent = {
	      enable = true;
	      enableExtraSocket = true;
	      enableSshSupport = true;
	      pinentry.package = pkgs.pinentry-gnome3; 
	      sshKeys = [ "1D0F13CF9061199762A8480B520999B9E78AE837" ];
	    };
	  };
	}
	{
	  programs = {
	    gpg = {
	      enable = true;
	      homedir = "${config.xdg.dataHome}/gnupg";
	      # homedir = "${config.home.homeDirectory}/d-sync/keys/gpg";
	      settings = {
	        default-key = "igoldlip@gmail.com";
	        default-recipient-self = true;
	      };
	    };
	  };
	}
	
	{ services.kdeconnect.enable = true; }
	{
	  xdg = {
	    enable = true;
	    cacheHome = config.home.homeDirectory + "/.local/cache";
	    userDirs = {
	      enable = true;
	      createDirectories = false;
	      documents =  "${config.home.homeDirectory}/docs";
	      download = "${config.home.homeDirectory}/dloads";
	      videos = "${config.home.homeDirectory}/media/vids";
	      music = "${config.home.homeDirectory}/media/music";
	      pictures = "${config.home.homeDirectory}/media/pics";
	      desktop = "${config.home.homeDirectory}/.local/share/desktop";
	      publicShare = "${config.home.homeDirectory}/.local/share/public";
	      templates = "${config.home.homeDirectory}/.local/share/templates";
	      extraConfig = {
	        xdg_screenshots_dir = "${config.xdg.userDirs.pictures}";
	      };
	    };
	
	    mimeApps = {
	      enable = true;
	      defaultApplications = {
	        "x-scheme-handler/magnet"="d-stuff.desktop";
	        "application/x-bittorrent"="d-stuff.desktop";
	        "application/postscript"="sioyek.desktop";
	        "application/pdf"="sioyek.desktop";
	        "image/png"="swayimg.desktop";
	        "image/jpeg"="swayimg.desktop";
	        "image/gif"="swayimg.desktop";
	        "application/rss+xml"="d-stuff.desktop";
	        "x-scheme-handler/mailto"="emacsmail.desktop";
	      };
	    };
	
	    portal = {
	      enable = true;
	      extraPortals = [
		        pkgs.xdg-desktop-portal-gnome
		        pkgs.xdg-desktop-portal-gtk
		    ];
	      config = {
	        ewm = {
	          default = "gnome;gtk";
	          "org.freedesktop.impl.portal.Access" = "gtk";
	          "org.freedesktop.impl.portal.Notification" = "gtk";
	          "org.freedesktop.impl.portal.Secret" = "gnome-keyring";
	        };
	      };
	    };
	  };
	  xdg.dataFile."applications/d-stuff.desktop".text = ''
	    [Desktop Entry]
	    Type=Application
	    Name=Stuff Handler
	    Exec=d-stuff %u
	  '';
	
	}
	{
	  programs.man = {
	    enable = true;
	    generateCaches = true; # will take little time
	  };
	}
	{
	  programs.git = {
	    enable = true;
	    package = pkgs.gitFull;
	    settings = {
	      safe.directory = "...";
	      user = {
	        name = "Dilip";
	        email = "igoldlip@gmail.com";
	      };
	
	      alias = {
	        a = "add";
	        b = "branch";
	        c = "commit";
	        ca = "commit --amend";
	        cm = "commit -m";
	        cho = "checkout";
	        d = "diff";
	        ds = "diff --staged";
	        p = "push";
	        pf = "push --force-with-lease";
	        pl = "pull";
	        l = "log";
	        r = "rebase";
	        s = "status --short";
	        ss = "status";
	        forgor = "commit --amend --no-edit";
	        graph = "log --all --decorate --graph --oneline";
	        logrep = "log --decorate --oneline --grep=";
	        oops = "checkout --";
	      };
	    };
	
	    ignores = ["*~" "*.swp" ".direnv" "node_modules"];
	
	    signing = {
	      key = "53F3BDB57ED8DC48";
	      signByDefault = true;
	    };
	  };
	
	}
	{
	  programs.direnv = {
	    enable = true;
	    nix-direnv.enable = true;
	  };
	}
	{
	  programs.foot = {
	    enable = true;
	    # server.enable = true; # use emacs dude!
	    settings = {
	      main = {
	        selection-target = "clipboard";
	      };
	      scrollback = {
	        lines = 10000;
	        multiplier = 3;
	      };
	      key-bindings = {
	        clipboard-copy = "Control+Shift+c";
	        clipboard-paste = "Control+Shift+v Control+y";
	        primary-paste = "Shift+Insert";
	      };
	      url = {
	        launch = "d-stuff \${url}";
	      };
	      mouse = {
	        hide-when-typing = "yes";
	      };
	      colors = {
	        alpha = lib.mkForce "0.9";
	      };
	    };
	  };
	}
	{
	  programs.zellij = {
	    enable = true;
	    settings = {
	    };
	  };
	}
	{
	  programs.emacs = {
	    enable = true;
	    package = pkgs.emacs-git-pgtk;
	    extraPackages = (epkgs: (with epkgs; [
	      treesit-grammars.with-all-grammars
	      vundo undo-fu-session
		    rainbow-delimiters colorful-mode
	      vertico orderless marginalia corfu cape
	      consult embark olivetti
	      # nerd-icons nerd-icons-completion nerd-icons-corfu nerd-icons-dired
	      embark-consult consult-eglot nix-ts-mode nix-mode
	      magit nov devdocs-browser reformatter
	      tempel eglot-tempel
	      jinx envrc ultra-scroll
	      # aria2 transmission
	      # ess 
	      # webfeeder engrave-faces
	      # toc-org
	      org-ql ox-hugo markdown-mode typst-ts-mode
	      flycheck consult-flycheck flycheck-eglot org-re-reveal
		    flycheck-vale gptel
		    verb forge melpaPackages.mastodon melpaPackages.telega
	      (pkgs.callPackage (inputs.ewm.outPath + "/nix/default.nix") {
	        withScreencastSupport = true;
	      })
	      # # dslide
	
	      (melpaBuild {
	        pname = "combobulate";
	        version = "20250621";
	        src = pkgs.fetchFromGitHub {
	          owner = "mickeynp";
	          repo = "combobulate";
	          rev = "17c71802eed2df1a6b25199784806da6763fb90c";
	          hash = "sha256-m+06WLfHkdlMkLzP+fah3YN3rHG0H8t/iWEDSrct25E=";
	        };
	      })
	
	      (melpaBuild {
	        pname = "org-super-links";
	        version = "20250621";
	        src = pkgs.fetchFromGitHub {
	          owner = "toshism";
	          repo = "org-super-links";
	          rev = "ce04bd04b20c498f6deb6338aff142f312144e3b";
	          hash = "sha256-9SGb+imKyi6J+mpBtkheOLAIpmd0E55i0BOGBT617gE=";
	        };
	      })
	
	      (melpaBuild {
	        pname = "claude-code-ide";
	        version = "20260217";
	        src = pkgs.fetchFromGitHub {
	          owner = "manzaltu";
	          repo = "claude-code-ide.el";
	          rev = "5f12e60c6d2d1802c8c1b7944bbdf935d5db1364";
	          sha256 = "sha256-tivRvgfI/8XBRImE3wuZ1UD0t2dNWYscv3Aa53BmHZE=";
	        };
	        packageRequires = with pkgs.emacsPackages; [
	          web-server
	          vterm
	          transient
	        ];
	      })
	
	    ])
	    );
	  };
	
	  xdg.configFile."emacs/init.el".source = config.lib.file.mkOutOfStoreSymlink "/home/${vars.username}/d-git/d-nix/gdk/configs/d-emacs/init.el";
	
	  xdg.configFile."emacs/early-init.el".source = config.lib.file.mkOutOfStoreSymlink "/home/${vars.username}/d-git/d-nix/gdk/configs/d-emacs/early-init.el";
	
	}
	{
	  programs.sioyek = {
	    enable = true;
	    bindings = {
	      "move_up" = ["k" "<C-p>"];
	      "move_down" = ["j" "<C-n>"];
	      "move_left" = "h";
	      "move_right" = "l";
	      "screen_down" = [ "d" "<C-v>" ];
	      "screen_up" = [ "u" "<A-v>" ];
	      "fit_to_page_width" = "<f9>";
	      "fit_to_page_width_smart" = "<f10>";
	      "toggle_fullscreen" = [ "f" "<f11>"  ];
	      "quit" = "Q";
	      "toggle_custom_color" = [ "<f8>" "I"];
	      "toggle_highlight" = "<f1>";
	      "command" = "<A-x>";
	      "toggle_dark_mode" = "i";
	      "toggle_presentation_mode" = "<f5>";
	      "toggle_statusbar" = "B";
	      "[m]control_menu(move_to_begin)" = "<C-a>";
	      "[m]control_menu(move_to_end)" = "<C-e>";
	      "[m]control_menu(delete_to_end)" = "<C-k>";
	      "[m]control_menu(move_word_forward)" = "<A-f>";
	      "[m]control_menu(move_word_backward)" = "<A-b>";
	      "[m]control_menu('down')" = "<C-n";
	      "[m]control_menu('up')" = "<C-p>";
	    };
	
	    config = {
	      # "background_color" = "0.0 0.0 0.0";
	      # "dark_mode_background_color" = "0.0 0.0 0.0";
	      # "custom_background_color" = "0.9 0.8 0.7";
	      # "custom_text_color" = "0.0 0.0 0.0";
	      # "dark_mode_contrast" = "1.0";
	      # "text_highlight_color" = "1.0 1.0 0.0";
	      "search_url_s" = "https://scholar.google.com/scholar?q";
	      "search_url_l" = "http://gen.lib.rus.ec/scimag/?q";
	      "search_url_g" = "https://www.google.com/search?q";
	      "middle_click_search_engine" = "s";
	      "shift_middle_click_search_engine" = "l";
	      "flat_toc" = "0";
	      "default_dark_mode" = "1";
	      "sort_bookmarks_by_location" = "1";
	      "collapsed_toc" = "1";
	      "ruler_mode" = "1";
	      "single_click_selects_words" = "1";
	      "#ignore_whitespace_in_presentation_mode" = "0";
	      "prerender_next_page_presentation" = "1";
	    };
	  };
	}
	{
	  home.packages = [ inputs.glide.packages.x86_64-linux.default ];
	  programs.librewolf = {
	    enable = true;
	    profiles.ihome = {
	      extraConfig = ''
	        
	      '';
	    };
	  };
	}
	{
	  services = {
	    mpd = {
	      enable = true;
	      musicDirectory = config.xdg.userDirs.music;
	      network = {
	        listenAddress = "127.0.0.1";
	        port = 6600;
	        startWhenNeeded = true;
	      };
	      extraConfig = ''
	      audio_output {
	        type            "pipewire"
	        name            "pipewire sound server"
	      }
	      auto_update "yes"
	      bind_to_address "@mpd"
	    '';
	    };
	
		mpd-mpris.enable = true;
	    playerctld.enable = true;
	
	  };
	}
	{
	  programs = {
	    mpv = {
	      enable = true;
	      scripts = with pkgs.mpvScripts; [ mpris manga-reader ];
	
	      bindings = {
	        l = "seek  5";
	        h = "seek -5";
	        k = "seek  30";
	        j = "seek -30";
	        J = "cycle sub";
	        K = "cycle sub down";
	        B = "no-osd add contrast -4; no-osd add brightness 4; show-text 'Black Level: \${brightness}'";
	        N = "no-osd add contrast 4; no-osd add brightness -4; show-text 'Black Level: \${brightness}'";
	        r = ''cycle-values video-rotate "90" "180" "270" "0"'';
	        a = "vf toggle hflip";
			"Alt+x" = "script-binding select/menu";
			s = "cycle_values sub-ass-override force no";
	
	      };
	
	      config = {
	        sub-auto = "fuzzy";
	        msg-level = "all=error";
	        ytdl-format = "bestvideo[height<1080]+bestaudio/best";
	        # ytdl-format = "bestvideo";
	        save-position-on-quit = true;
			keep-open = true;
			scale-antiring = "0.6";
			dither-depth = "8";
	        slang = "eng,en,eng,english";
	        alang = "jp,jpn,en,eng";
	        sub-font = lib.mkForce "Gandhi Sans";
	        sub-font-size = "50";
	        speed = "1.5";
			sub-ass-override = "no";
			sub-ass-style-overrides = "playresx=1440,playresy=900,Kerning=yes";
			sub-color = "#FFFFFF";
			sub-margin-y = "40";
			sub-border-size = "2.4";
			sub-border-color = "#FF000000";
			sub-shadow-color = "#A0000000";
			sub-shadow-offset = "0.75";
			sub-bold = "yes";
	      };
	    };
	  };
	}
	{
	  programs = {
	    yt-dlp = {
	      enable = true;
	      settings = {
	        embed-thumbnail = true;
	        embed-metadata = true;
	        embed-subs = true;
	        sub-langs = "en";
	      };
	    };
	  };
	}
	{
	  programs.swayimg = {
	    enable = true;
	    settings = {
	      viewer = {
	        window = "#00000000";
	        scale = "fit";
	      };
	        "keys.viewer" = {
	          "F1" = "help";
	          "Ctrl+h" = "help";
	          "Ctrl+a" = "first_file";
	          "Ctrl+e" = "last_file";
	          "p" = "prev_file";
	          "n" = "next_file";
	          "Space" = "next_file";
	          "Shift+d" = "prev_dir";
	          "d" = "next_dir";
	          "Shift+o" = "prev_frame";
	          "o" = "next_frame";
	          "c" = "skip_file";
	          "F5" = "slideshow";
	          "s" = "animation";
	          "f" = "fullscreen";
	          "Return" = "mode";
	          "h" = "step_left 10";
	          "l" = "step_right 10";
	          "k" = "step_up 10";
	          "j" = "step_down 10";
	          "Equal" = "zoom +10";
	          "Plus" = "zoom +10";
	          "Minus" = "zoom -10";
	          "Shift+w" = "zoom width";
	          "Shift+h" = "zoom height";
	          "bracketleft" = "rotate_left";
	          "bracketright" = "rotate_right";
	          "r" = "rotate_right";
	          "Shift+r" = "rotate_left";
	          "Shift+Delete" = "exec rm -f '%' && echo 'File removed: %'; skip_file";
	          "m" = "flip_vertical";
	          "Shift+m" = "flip_horizontal";
	          "q" = "exit";
	        };
	    };
	  };
	}
	
	inputs.mango.hmModules.mango
	  {
	    wayland.windowManager.mango = {
	      enable = true;
	      systemd = {
	        enable = true;
	        xdgAutostart = true;
	      };
	    };
	  }
	{
	  home.packages = with pkgs; [
	    # screenshot
	    grim slurp
		libreoffice-fresh
	
	    libnotify libsixel
	    brightnessctl
	    wtype gtk3
	    swaybg swayimg wlsunset
	    hyprshot gpu-screen-recorder noctalia-shell vicinae
	
	    wl-screenrec wl-mirror wlr-randr
	    wl-clipboard-rs xwayland-satellite
	    mupdf poppler-utils ghostscript # for doc-view
	    uv prettier ruff
	
	    pavucontrol pulsemixer playerctl
	    transmission_4-gtk
	
	    mpc ani-cli
	  ];
	}
	{
	  services.hypridle = let
	    hyprlock = lib.getExe pkgs.hyprlock;
		noctalia = lib.getExe pkgs.noctalia-shell;
	    brightness = lib.getExe pkgs.brightnessctl;
	    niri = lib.getExe pkgs.niri;
	    mmsg = lib.getExe' inputs.mango.packages.x86_64-linux.mango "mmsg";
	    timeout = 200; # base timer to act upon
	    in {
	    enable = true;
	    settings ={
	      general = {
	        lock_cmd = "${noctalia} ipc call lockScreen lock";
	        before_sleep_cmd = "${pkgs.systemd}/bin/loginctl lock-session";
	      };
	
	      listener = [
	        {
	          timeout = timeout - 50;
	          on-timeout = "${brightness} -s set 5%";
	          on-resume = "${brightness} -r";
	        }
	        {
	          timeout = timeout;
	          on-timeout = "loginctl lock-session";
	        }
	        {
	          timeout = timeout + 10;
	          on-timeout = "${niri} msg action power-off-monitors || ${mmsg} -d disable_monitor";
	          on-resume = "${niri} msg action power-on-monitors || ${mmsg} -d enable_monitor";
	        }
	        {
	          timeout = timeout * 5;
	          on-timeout = "systemctl suspend";
	        }
	      ];
	    };
	  };
	}
	{
	  stylix = {
	    enable = true;
	
	    icons = { # watch out soon stylix might implement this
	      enable = true;
	      dark = "Papirus-Dark";
	      package = pkgs.papirus-icon-theme;
	    };
	
	    targets = {
	      emacs.enable = false;
	      librewolf.profileNames = [ "ihome" ];
	      gtk.extraCss = ''
	            @define-color light_1 #ffffff;
	            @define-color dark_5 #000000;
	      '';
	    };
	  };
	}
	{
	  programs = {
	    eza = {
	      enable = true;
	      extraOptions = ["--group-directories-first" "--header"];
	    };
	
	    ripgrep = {
	      enable = true;
	      arguments = [
	        "--max-columns-preview"
	        # "--colors=line:style:bold"
	        "--ignore-case"
	        "--follow"
	        "--null" "--line-buffered" "--max-columns=1000" "--smart-case" "--no-heading" "--with-filename" "--line-number"
	      ];
	    };
	
	    btop = {
	      enable = true;
	      settings = {
	        # color_theme = "default";
	        theme_background = false;
	        vim_keys = true;
	        shown_boxes = "proc cpu";
	        rounded_corners = true ;
	        graph_symbol = "block";
	        proc_sorting = "memory";
	        proc_reversed = false;
	        proc_gradient = true;
	      };
	    };
	
	    bat = {
	      enable = true;
	    };
	
	    ssh = {
	      enable = true;
	      enableDefaultConfig = false;
	      extraOptionOverrides = {
	        SetEnv = "TERM=xterm-256color";
	      };
	      matchBlocks."*" = {
	        forwardAgent = false;
	        addKeysToAgent = "no";
	        compression = false;
	        serverAliveInterval = 0;
	        serverAliveCountMax = 3;
	        hashKnownHosts = false;
	        userKnownHostsFile = "~/.ssh/known_hosts";
	        controlMaster = "no";
	        controlPath = "~/.ssh/master-%r@%n:%p";
	        controlPersist = "no";
	        forwardX11Trusted = true;
	        forwardX11 = true;
	      };
	    };
	
	    fzf = {
	      enable = true;
	      defaultCommand = "fd --type f";
	    };
	
	  };
	}
	{
	  home = {
	    sessionVariables = {
	      EDITOR = "emacsclient -c";
	      VISUAL = "$EDITOR";
	      GRIM_DEFAULT_DIR = "$HOME/pics/sshots/";
	      STARDICT_DATA_DIR = "$HOME/d-git/d-bin/treasure/dict/";
	      LESS = "-J -i -W --status-line --incsearch --use-color -R";
	      COLORTERM="truecolor";
	    };
	    sessionPath = [ "$HOME/.local/bin" "$HOME/.bin" ];
	    keyboard.options = [ "ctrl:nocaps" ];
	    preferXdgDirectories = true;
	
	    shellAliases = {
	      cleanup = "doas nix-collect-garbage --delete-older-than 7d";
	      bloat = "nix path-info -Sh /run/current-system";
	      ytmp3 = "yt-dlp -x --continue --add-metadata --embed-thumbnail --audio-format mp3 --audio-quality 0 -o '%(title)s.%(ext)s' ";
	      cat = "bat";
	      grep = "rg";
	      du = "dust";
	      ls = "eza -h --git --icons --color=auto --group-directories-first -s extension";
	      l = "ls -lF --time-style=long-iso --icons";
	      la = "eza -lah --tree";
	      tree = "eza --tree --icons";
	      http = "python3 -m http.server";
	      burn = "pkill -9";
	      diff = "diff --color=auto";
	      ".1" = "cd ..";
	      ".2" = "cd ../..";
	      ".3" = "cd ../../..";
	      c = "clear";
	      v = "emacsclient -nw";
	      e = "emacsclient -nw";
	      emd = "emacs --daemon";
	      cp = "cp -iv";
	      mv = "mv -iv";
	      rm = "rm -vI";
	      bc = "bc -ql";
	      mkd = "mkdir -pv";
	      gc = "git clone --depth=1";
	      sioyek = "sioyek --new-window";
	      hyprunlock = "pkill -SIGUSR1 hyprlock";
	      rebuild = "nixos-rebuild switch --flake ~/d-git/d-nix#host ";
	      testrebuild = "nixos-rebuild test --flake ~/d-git/d-nix#host";
	      ytdl = "yt-dlp --embed-metadata --embed-subs";
	      fcd = "cd $(fd -t d | fzf)";
	      open = "emacsclient -t $(fd -t f | fzf)";
	    };
	
	  };
	
	}
	{
	  home.packages = with pkgs; [
	    zip unzip # archives
	    ffmpeg-full sdcv nq
	    # utils
	    dust fd wget ripgrep-all file
	  ];
	}
	{
	  programs.starship = {
	    enable = true;
	     settings = {
	      add_newline = true;
	      scan_timeout = 5;
	
	      line_break.disabled = false;
	
	      character = {
	        success_symbol = " ";
	        error_symbol = "󰘧";
	      };
	
	      hostname = {
		      ssh_only = true;
		      format = "[$hostname](bold blue) ";
		      disabled = false;
	      };
	    };
	  };
	}
	{
	  programs = {
	    fish = {
	      enable = true;
	      binds = {
	        "alt-backspace".command = "backward-kill-word";
	      };
	
	    };
	    nushell = {enable = true;};
	    bash = {enable = true;};
	  };
	}
	{
	  home.packages = with pkgs; [
	    # texlive.combined.scheme-full
	    typst # ollama
	  ];
	}
	{
	  programs.aria2 = {
	    enable = true;
	    settings = {
	      dir = config.xdg.userDirs.download;
	      file-allocation = "none";
	      log-level = "warn";
	      split = "10";
	      max-connection-per-server = 10;
	      min-split-size = "5m";
	      bt-max-peers = "0";
	      bt-request-peer-speed-limit = "0";
	      max-overall-upload-limit = "512k";
	      bt-external-ip = "127.0.0.1";
	      dht-listen-port = "6882";
	      enable-dht = "true";
	      enable-peer-exchange = "true";
	      listen-port = "6881";
	      bt-force-encryption = "true";
	      bt-min-crypto-level = "arc4";
	      bt-require-crypto = "true";
	      follow-torrent = "mem";
	      seed-ratio = "100";
	      seed-time = "0";
	      socket-recv-buffer-size = "1m";
	      event-poll = "epoll";
	      realtime-chunk-checksum = "true";
	      allow-overwrite = "true";
	      always-resume = "true";
	      auto-file-renaming = "false";
	      continue = "true";
	      rpc-save-upload-metadata = "false";
	    };
	  };
	}
	{
	  programs.rofi = {
	    enable = true;
		plugins = with pkgs; [ rofi-nerdy rofi-calc rofi-emoji ];
		modes = [ "drun" "run" "window" "calc" "nerdy" "emoji" ];
	    extraConfig = {
	      modi = "drun,run,window,combi";
		  combi-modes = [ "window" "drun" "run" "nerdy" "emoji" ];
	      show-icons = true;
	      hide-scrollbar = true;
	      display-drun = " Apps ";
	      display-run = "  Run ";
	      display-window = "󰍲   Window ";
	      sidebar-mode = true;
	      drun-show-actions = true;
	    };
		theme = {
		  "@import" = "dmenu";
		};
	  };
	}
	{ home.packages = with pkgs; [ libnotify nautilus pandoc groff mupdf keepassxc easyeffects jaq
	  #libreoffice-fresh
	]; }
	{
	
	  home = with pkgs;
	    let
	      mySpells = aspellWithDicts (dicts: with dicts; [ en en-computers ]);
	    in
	      {
	        file.".aspell.conf".text = ''
	          dict-dir ${mySpells}/lib/aspell/
	          add-extra-dicts en-computers.rws
	        '';
	        packages = [
	          # languagetool
	          mySpells
	          hunspell hunspellDicts.en_US-large hunspellDicts.en_GB-large
	        ];
	      };
	}
  ];

  # NEVER EVER TOUCH IT ⚠️
  home.stateVersion = "25.05"; # refer manual !

  # home configuration ends here
}
