#+title: Emacs on Droid


* Emacs proves again on Android.

Get apk builds officially from: [[https://sourceforge.net/projects/android-ports-for-gnu-emacs/files/termux/][Sourceforge]].

The lead dev, Po Lu, has added so many features on my request on telegram. He even made extra build with termux.
Such a precious software is 100% usable on Android now!

My config is compatible and I use it for reading news/rss (elfeed) and org file.

** Instruction to manually sign apks
No need to do it manually, the builds on Sourceforge already has been signed.

You can go ahead if you want to use [[https://github.com/t184256/nix-on-droid][nix-on-droid]].

Thanks to this blog: [[https://marek-g.github.io/posts/tips_and_tricks/emacs_on_android/]]

Note: You need to generate keystore

- For Termux
#+begin_src sh
  $ apktool d <termux.apk>.
  $ apktool b <termux_folder> -o termux_for_emacs.apk.
  $ jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ~/.android/debug.keystore termux_for_emacs.apk androiddebugkey.

#+end_src

- For emacs
  #+begin_src sh
    $ apktool d <emacs.apk>

    # Add android:sharedUserId="com.termux" android:sharedUserLabel="@string/shared_user_label" to Emacs’ AndroidManifest.xml.
    # Copy @string/shared_user_label from Termux’s res/values/strings.xml to Emacs’ resources. The content should be
    # like this:
    # <resources>
    #  ...
    #  <string name="shared_user_label">Termux user</string>
    # </resources>

    ## Only after above steps

    $ apktool b emacs_and_termux -o emacs_for_termux.apk.
    $ jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore ~/.android/debug.keystore emacs_for_termux.apk androiddebugkey.

  #+end_src


* Set env in early-init.el

#+begin_src emacs-lisp
  (setenv "PATH" (format "%s:%s" "/data/data/com.termux/files/usr/bin"
                 (getenv "PATH")))
  (setenv "LD_LIBRARY_PATH" (format "%s:%s"
                    "/data/data/com.termux/files/usr/lib"
                    (getenv "LD_LIBRARY_PATH")))
  (push "/data/data/com.termux/files/usr/bin" exec-path)

#+end_src

* Installation

I use syncthing to sync files from pc to Android.

1. Install termux first and then emacs, then ~pkg update~ if you need it.
2. Open emacs, ~rm -rf .emacs*~ to remove all files.

#+begin_src bash
  mkdir .config/emacs
  ln -s /storage/emulated/0/d-sync d-sync
  ln -s /storage/emulated/0/d-git d-git
  ln -s ~/d-sync/fonts fonts # we need TTF fonts for android
  cd .config/emacs
  ln -s /storage/emulated/0/.../d-emacs/early-init.el early-init.el
  ln -s /storage/emulated/0/.../d-emacs/init.el init.el
  ln -s /storage/emulated/0/.../d-emacs/lisp lisp
  ln -s /storage/emulated/0/.../d-emacs/templates templates
  ln -s ~/d-sync/feeds/elfeed.org elfeed.org

  # for elfeed and theme
  mkdir -p var
  cd var
  ln -s ~/d-git/d-theme theme
  ln -s ~/d-sync/feeds/elfeed elfeed

#+end_src


** Misc package

Downloadable from termux
#+begin_src bash
  enchant
  aspell
  clang # for compiling
  ripgrep # rocket
  bat
  git

#+end_src
