launch_command: loadpage library ;; flush ;; history clear
video:
- Reload updated video: run rm '~/.cache/youtube-tui/info/${id}.json' ;; video ${id}
- Play video: run ${video-player} '${embed-url}'
- Play audio: run ${terminal-emulator} ${video-player} '${embed-url}' --no-video
- Play audio (loop): run ${terminal-emulator} ${video-player} '${embed-url}' --no-video --loop-file=inf
- View channel: channel ${channel-id}
- Open in browser: run ${browser} '${url}'
- Toggle bookmark: togglemark ${id}
- Save video to library: bookmark ${id} ;; run rm -rf '${save-path}${id}.*' ;; run ${terminal-emulator} ${youtube-downloader} '${embed-url}' -o '${save-path}%(title)s[%(id)s].%(ext)s'
- Save audio to library: bookmark ${id} ;; run rm -rf '${save-path}${id}.*' ;; run ${terminal-emulator} ${youtube-downloader} '${embed-url}' -x -o '${save-path}%(title)s[%(id)s].%(ext)s'
- 'Mode: ${provider}': switchprovider
saved_video:
- Reload updated video: run rm '~/.cache/youtube-tui/info/${id}.json' ;; video ${id}
- '[Offline] Play saved file': run find ${save-path} | grep ${id} | ${video-player} --playlist=- --force-window
- '[Offline] Play saved file (audio)': run ${terminal-emulator} bash -c 'find ${save-path} | grep ${id} | ${video-player} --playlist=- --no-video'
- '[Offline] Play saved file (audio loop)': run ${terminal-emulator} bash -c 'find ${save-path} | grep ${id} | ${video-player} --playlist=- --no-video --loop'
- View channel: channel ${channel-id}
- Open in browser: run ${browser} '${url}'
- Toggle bookmark: togglemark ${id}
- Redownload video to library: bookmark ${id} ;; run rm ${save-path}*${id}*.* ;; run ${terminal-emulator} ${youtube-downloader} ${embed-url} -o '${save-path}%(title)s[%(id)s].%(ext)s'
- Redownload audio to library: bookmark ${id} ;; run rm ${save-path}*${id}*.* ;; run ${terminal-emulator} ${youtube-downloader} ${embed-url} -x -o '${save-path}%(title)s[%(id)s].%(ext)s'
- Delete saved file: run rm ${save-path}*${id}*.*
playlist:
- Switch view: '%switch-view%'
- Reload updated playlist: run rm ~/.cache/youtube-tui/info/${id}.json ;; reload
- Play all (videos): run ${video-player} ${all-videos}
- Play all (audio): run ${terminal-emulator} ${video-player} ${all-videos} --no-video
- Shuffle play all (audio loop): run ${terminal-emulator} ${video-player} ${all-videos} --no-video --shuffle --loop-playlist=inf
- View channel: channel ${channel-id}
- Open in browser: run ${browser} '${url}'
- Link Handler: d-stuff '${url}'
- Toggle bookmark: togglemark ${id}
- Save playlist videos to library: bookmark ${id} ;; run rm -rf '${save-path}*${id}*' ;; run ${terminal-emulator} bash -c "${youtube-downloader} ${all-videos} -o '"'${save-path}${title}[${id}]/%(title)s[%(id)s].%(ext)s'"'"
- Save playlist audio to library: bookmark ${id} ;; run rm -rf '${save-path}*${id}*' ;; run ${terminal-emulator} bash -c "${youtube-downloader} ${all-videos} -x -o '"'${save-path}${title}[${id}]/%(title)s[%(id)s].%(ext)s'"'"
- 'Mode: ${provider}': switchprovider
saved_playlist:
- Switch view: '%switch-view%'
- Reload updated playlist: run rm ~/.cache/youtube-tui/info/${id}.json ;; reload
- '[Offline] Play all (videos)': run find ${save-path} | grep ${id} | ${video-player} --playlist=- --force-window
- '[Offline] Play all (audio)': run ${terminal-emulator} bash -c 'find ${save-path} | grep ${id} | ${video-player} --playlist=- --no-video'
- '[Offline] Shuffle play all (audio loop)': run ${terminal-emulator} bash -c 'find ${save-path} | grep ${id} | ${video-player} --playlist=- --no-video --loop-playlist=inf'
- View channel: channel ${channel-id}
- Open in browser: run ${browser} '${url}'
- Toggle bookmark: togglemark ${id}
- Redownload playlist videos to library: bookmark ${id} ;; run rm -rf ${save-path}*${id}* ;; run ${terminal-emulator} bash -c "${youtube-downloader} ${all-videos} -o '"'${save-path}${title}[${id}]/%(title)s[%(id)s].%(ext)s'"'"
- Redownload playlist audio to library: bookmark ${id} ;; run rm -rf ${save-path}*${id}* ;; run ${terminal-emulator} bash -c "${youtube-downloader} ${all-videos} -x -o '"'${save-path}${title}[${id}]/%(title)s[%(id)s].%(ext)s'"'"
- Delete saved files: run rm -rf ${save-path}*${id}*
