End:
  0: ClearHistory
Down:
  0: MoveDown
Esc:
  0: Deselect
'l':
  0: MoveRight
Home:
  0: FirstHistory
F5:
  0: Reload
'q':
  0: Exit
Left:
  0: MoveLeft
  4: Back
'r':
  2: Reload
'h':
  0: MoveLeft
'v':
  2: Paste
':':
  0: StartCommandCapture
Backspace:
  0: Back
'k':
  0: MoveUp
Enter:
  0: Select
Up:
  0: MoveUp
'j':
  0: MoveDown
Right:
  0: MoveRight
