mouse_support: true
invidious_instance: https://vid.puffyan.us
max_watch_history: 50
allow_unicode: true
message_bar_default: All good :)
images: Sixels
refresh_after_modifying_search_filters: true
image_index: 4
provider: YouTube
env:
  video-player: mpv
  browser: firefox
  download-path: ~/dloads/%(title)s-%(id)s.%(ext)s
  terminal-emulator: footclient -e
  youtube-downloader: yt-dlp
  save-path: ~/.local/share/youtube-tui/saved/
  link-hanlder: d-stuff
